// REGIONGEN. A region is several settlements, each generated by the ordinary CityGen pipeline,
// placed on one regional terrain and tied together by infrastructure that is planned BEFORE any
// settlement's own fabric exists.
//
//   1. regional terrain            one elevation function for the whole region
//   2. regional plan               how the population is shared out: scales and roles
//   3. settlement sites            where each one goes, and how it relates to its neighbours
//   4. regional infrastructure     intercity roads and highways, regional rail, protected land
//   5. interface zones             what the land between neighbouring settlements becomes
//   6. settlements                 CityGen, once per settlement, with the regional context
//   7. stitching and statistics    regional lines meet the settlements' own gateways and portals
//
// Nothing of CityGen is duplicated: a settlement is a CityModel. Settlements are never merged,
// even when their fabrics touch; each keeps its administrative identity, centre and street grid.

import { SeededRandom, makeNoise2D, fbm } from '../core/SeededRandom.js';
import { DEFAULT_CONFIG, SIZE_PRESETS, createCityModel, record } from '../core/CityModel.js';
import { runPipelineSync, runPipeline } from '../core/Pipeline.js';
import { leastCostPath, NEIGH16 } from '../algorithms/LeastCostPath.js';
import { fitAlignment } from '../algorithms/Alignment.js';
import { simplifyDP, polylineLength, pointSegment, circlePolygon } from '../core/Geometry.js';
import { labelComponents } from '../core/Raster.js';
import { traceRegionRings } from '../algorithms/PolygonUtils.js';
import { PLANNING_PROFILES } from './PlanningProfiles.js';

export const SETTLEMENT_SCALES = ['PRIMARY_CITY', 'MAJOR_CITY', 'SECONDARY_CITY', 'SMALL_CITY', 'SPECIALIZED_TOWN', 'LOCAL_TOWN'];
export const SETTLEMENT_ROLES = ['MIXED', 'INDUSTRIAL', 'PORT', 'UNIVERSITY', 'ADMINISTRATIVE', 'LOGISTICS', 'RESORT', 'MILITARY'];
export const INTERFACE_TYPES = ['URBAN_INFILL', 'COMMERCIAL_CORRIDOR', 'INDUSTRIAL_BUFFER', 'GREEN_WEDGE', 'TRANSPORT_CORRIDOR', 'MIXED_EDGE', 'HARD_INFRASTRUCTURE_EDGE'];
export const RELATIONS = ['SEPARATE', 'NEAR_TOUCHING', 'GLUED', 'CONTINUOUS_METROPOLITAN'];
export const DEFAULT_REGION_CONFIG = { seed: 'region-1', regionalPopulationTarget: 1000000, structure: 'auto', coast: 'auto' };

const CELL = 250; // regional raster cell (m)
const DENSITY = 9100; // people per km2 of urban land, as in the city brief
const radiusFor = (pop) => Math.sqrt(pop / DENSITY / Math.PI) * 1000;
const sizeFor = (pop) => (pop > 700000 ? 'metropolis' : pop >= 250000 ? 'major' : pop >= 80000 ? 'medium' : 'small');
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const smooth = (a, b, x) => { const t = clamp((x - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); };

export function createRegionModel(input = {}) {
  const config = { ...DEFAULT_REGION_CONFIG, ...input };
  config.regionalPopulationTarget = clamp(Math.round(Number(config.regionalPopulationTarget) || 1e6), 300000, 12000000);
  return {
    seed: config.seed, config,
    regionalPopulationTarget: config.regionalPopulationTarget,
    terrain: null, regionalPlan: null,
    settlements: [], regionalRoads: [], regionalRail: [], regionalAnchors: [],
    interfaceZones: [], protectedAreas: [], relations: [],
    stats: {}, metadata: { log: [], timings: {} },
  };
}

// ---------------------------------------------------------------- 1. terrain
function planRegionTerrain(region, rng, log) {
  const P = region.regionalPopulationTarget;
  const size = Math.round(clamp(18000 + 26000 * Math.sqrt(P / 1e6), 34000, 104000) / 1000) * 1000;
  const w = Math.round(size / CELL), h = w, n = w * h;
  const noise = makeNoise2D(rng.int(1e9)), noise2 = makeNoise2D(rng.int(1e9));
  const coastal = region.config.coast === 'auto' ? rng.chance(0.7) : region.config.coast === 'yes';
  const seaAngle = rng.range(0, Math.PI * 2), sx = Math.cos(seaAngle), sy = Math.sin(seaAngle);
  const hillAngle = seaAngle + Math.PI + rng.range(-0.8, 0.8), hx = Math.cos(hillAngle), hy = Math.sin(hillAngle);
  const half = size / 2;
  // rivers: from the inland side towards the sea (or across the region), meandering
  const rivers = [];
  const count = rng.chance(0.55) ? 1 : 2;
  for (let k = 0; k < count; k++) {
    const a0 = seaAngle + Math.PI + rng.range(-0.9, 0.9), a1 = seaAngle + rng.range(-0.7, 0.7);
    const p0 = { x: half + Math.cos(a0) * half * 1.3, y: half + Math.sin(a0) * half * 1.3 }, p1 = { x: half + Math.cos(a1) * half * 1.3, y: half + Math.sin(a1) * half * 1.3 };
    const len = Math.hypot(p1.x - p0.x, p1.y - p0.y), nx = -(p1.y - p0.y) / len, ny = (p1.x - p0.x) / len, ph = rng.range(0, 6), amp = rng.range(0.05, 0.12) * len;
    const pts = [];
    for (let t = 0; t <= 1.0001; t += 1 / 80) { const off = amp * (Math.sin(t * 5.3 + ph) * 0.6 + Math.sin(t * 11.7 + ph * 2) * 0.3 + noise2(t * 6, k * 9.1) * 0.5); pts.push({ x: p0.x + (p1.x - p0.x) * t + nx * off, y: p0.y + (p1.y - p0.y) * t + ny * off }); }
    rivers.push({ points: pts, width: 260 - 60 * k });
  }
  // base elevation on the coarse grid (m)
  const base = new Float32Array(n);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const px = (x + 0.5) * CELL, py = (y + 0.5) * CELL, u = (px - half) / half, v = (py - half) / half;
    let e = 22 + 70 * Math.max(0, fbm(noise, px / 16000, py / 16000, 4) + 0.1);
    const inland = u * hx + v * hy;
    e += 300 * smooth(0.35, 1.05, inland + 0.25 * fbm(noise2, px / 9000, py / 9000, 3)); // an upland flank
    if (coastal) { const s = u * sx + v * sy + 0.16 * fbm(noise2, px / 12000 + 7, py / 12000, 3); if (s > 0.5) e = Math.min(e, 6) - (s - 0.5) * 160 - 1.5; else e += 0; }
    base[y * w + x] = e;
  }
  const riverNear = new Uint8Array(n);
  const riverDist = (px, py) => { let d = Infinity, wd = 0; for (const r of rivers) for (let i = 0; i + 1 < r.points.length; i++) { const ps = pointSegment(px, py, r.points[i].x, r.points[i].y, r.points[i + 1].x, r.points[i + 1].y); if (ps.d - r.width / 2 < d) { d = ps.d - r.width / 2; wd = r.width; } } return [d, wd]; };
  for (let i = 0; i < n; i++) if (riverDist(((i % w) + 0.5) * CELL, (Math.floor(i / w) + 0.5) * CELL)[0] < 1600) riverNear[i] = 1;
  const baseAt = (px, py) => {
    const fx = clamp(px / CELL - 0.5, 0, w - 1.001), fy = clamp(py / CELL - 0.5, 0, h - 1.001), x0 = Math.floor(fx), y0 = Math.floor(fy), tx = fx - x0, ty = fy - y0;
    return (base[y0 * w + x0] * (1 - tx) + base[y0 * w + x0 + 1] * tx) * (1 - ty) + (base[(y0 + 1) * w + x0] * (1 - tx) + base[(y0 + 1) * w + x0 + 1] * tx) * ty;
  };
  // the one elevation function of the region: every settlement's terrain is a window of it
  const elevationAt = (px, py) => {
    let e = baseAt(px, py);
    const ci = clamp(Math.floor(py / CELL), 0, h - 1) * w + clamp(Math.floor(px / CELL), 0, w - 1);
    if (riverNear[ci] && e > -1) {
      const [d] = riverDist(px, py);
      if (d < 0) e = -3.5;
      else if (d < 900) e = Math.min(e, 2 + (e - 2) * smooth(0, 900, d) + 0); // a broad valley floor
    }
    return e;
  };
  const elevation = new Float32Array(n), water = new Uint8Array(n), slope = new Float32Array(n), buildability = new Float32Array(n);
  for (let i = 0; i < n; i++) { elevation[i] = elevationAt(((i % w) + 0.5) * CELL, (Math.floor(i / w) + 0.5) * CELL); water[i] = elevation[i] < 0 ? 1 : 0; }
  let waterCells = 0;
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const i = y * w + x, E = (xx, yy) => Math.max(0, elevation[clamp(yy, 0, h - 1) * w + clamp(xx, 0, w - 1)]);
    slope[i] = Math.hypot((E(x + 1, y) - E(x - 1, y)) / (2 * CELL), (E(x, y + 1) - E(x, y - 1)) / (2 * CELL));
    buildability[i] = water[i] ? 0 : 1 - smooth(0.035, 0.13, slope[i]);
    waterCells += water[i];
  }
  // open sea = water connected to the edge in a large body; rivers are narrow water
  const sea = new Uint8Array(n);
  { const comps = labelComponents(water, w, h); comps.sizes.forEach((sz, l) => { if (sz > 0.01 * n) for (let i = 0; i < n; i++) if (comps.labels[i] === l) sea[i] = 1; }); }
  region.terrain = { size, cell: CELL, w, h, n, elevation, water, sea, slope, buildability, rivers, coastal, seaAngle: coastal ? seaAngle : null, elevationAt, waterShare: waterCells / n, maxElevation: elevation.reduce((a, b) => Math.max(a, b), 0) };
  log(`region ${size / 1000} km square, ${coastal ? 'coastal' : 'inland'}, ${rivers.length} river${rivers.length > 1 ? 's' : ''}, ${Math.round((100 * waterCells) / n)}% water`);
}

// ---------------------------------------------------------------- 2. population -> settlements
const NAME_A = ['Vel', 'Kar', 'Mor', 'Tes', 'Al', 'Bren', 'Dor', 'Est', 'Fal', 'Gar', 'Hal', 'Ist', 'Lor', 'Mar', 'Nor', 'Or', 'Pel', 'Quen', 'Ros', 'Sar', 'Tor', 'Ul', 'Var', 'Wes', 'Yar', 'Zel'];
const NAME_B = ['mora', 'th', 'ia', 'den', 'holm', 'ova', 'ine', 'ara', 'wick', 'stad', 'mont', 'bury', 'esti', 'ano', 'field', 'haven', 'ford', 'grad', 'ona', 'ey'];

function planSettlementSystem(region, rng, log) {
  const P = region.regionalPopulationTarget, cfg = region.config;
  const structure = cfg.structure !== 'auto' ? cfg.structure : rng.pick(['dominant', 'dominant', 'balanced', 'polycentric']);
  const share = { dominant: rng.range(0.42, 0.55), balanced: rng.range(0.3, 0.38), polycentric: rng.range(0.2, 0.27) }[structure];
  const alpha = { dominant: 1.0, balanced: 0.78, polycentric: 0.55 }[structure];
  const primary = clamp(Math.round((share * P) / 1000) * 1000, 120000, SIZE_PRESETS.metropolis.popRange[1]);
  // rank-size: the k-th settlement is primary / k^alpha, until the regional target is met
  const pops = [primary];
  let sum = primary;
  for (let k = 2; k <= 40 && sum < P * 0.985; k++) {
    let p = primary / k ** alpha * rng.range(0.85, 1.15);
    p = clamp(Math.round(p / 1000) * 1000, 20000, Math.min(primary * 0.92, SIZE_PRESETS.metropolis.popRange[1]));
    if (sum + p > P * 1.03) p = Math.round((P - sum) / 1000) * 1000;
    if (p < 20000) break;
    pops.push(p); sum += p;
  }
  const names = new Set();
  const settlements = pops.map((pop, k) => {
    const scale = k === 0 ? 'PRIMARY_CITY' : pop >= 250000 ? 'MAJOR_CITY' : pop >= 100000 ? 'SECONDARY_CITY' : pop >= 40000 ? 'SMALL_CITY' : 'LOCAL_TOWN';
    let name; do { name = rng.pick(NAME_A) + rng.pick(NAME_B); } while (names.has(name)); names.add(name);
    // centres are not equal: the regional hierarchy gives each a different weight
    const centreStrength = k === 0 ? 'DOMINANT' : k === 1 && pop > 0.45 * primary ? 'STRONG' : pop >= 60000 ? 'ORDINARY' : rng.chance(0.5) ? 'ORDINARY' : 'WEAK';
    return { id: `settlement_${String(k + 1).padStart(2, '0')}`, type: 'settlement', createdByStage: 'regionalPlan', name, rank: k + 1, scale, role: 'MIXED', populationTarget: pop, centreStrength, citySize: sizeFor(pop), radius: radiusFor(pop) };
  });
  region.regionalPlan = { structure, primaryShare: primary / P, rankSizeExponent: alpha, allocatedPopulation: sum, settlementCount: settlements.length };
  region.settlements = settlements;
  log(`${structure} region: ${settlements.length} settlements, primary city ${(primary / 1000).toFixed(0)}k (${Math.round((100 * primary) / P)}% of ${(P / 1e6).toFixed(2)}M), ${settlements.filter((s) => s.scale === 'MAJOR_CITY').length} major, ${settlements.filter((s) => s.scale === 'SECONDARY_CITY').length} secondary, ${settlements.filter((s) => s.scale === 'SMALL_CITY').length} small, ${settlements.filter((s) => s.scale === 'LOCAL_TOWN').length} towns`);
}

// ---------------------------------------------------------------- 3. sites and relations
function planSites(region, rng, log) {
  const T = region.terrain, { w, h, size } = T, P = region.regionalPopulationTarget;
  // summed-area table of buildability, for "how much usable land is around here"
  const sat = new Float64Array((w + 1) * (h + 1));
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) sat[(y + 1) * (w + 1) + x + 1] = T.buildability[y * w + x] + sat[y * (w + 1) + x + 1] + sat[(y + 1) * (w + 1) + x] - sat[y * (w + 1) + x];
  const boxMean = (cx, cy, half) => { const x0 = clamp(Math.floor((cx - half) / CELL), 0, w), x1 = clamp(Math.ceil((cx + half) / CELL), 0, w), y0 = clamp(Math.floor((cy - half) / CELL), 0, h), y1 = clamp(Math.ceil((cy + half) / CELL), 0, h); const a = (x1 - x0) * (y1 - y0); return a ? (sat[y1 * (w + 1) + x1] - sat[y0 * (w + 1) + x1] - sat[y1 * (w + 1) + x0] + sat[y0 * (w + 1) + x0]) / a : 0; };
  const waterWithin = (cx, cy, r, seaOnly) => { const m = seaOnly ? T.sea : T.water, c = Math.ceil(r / CELL), x0 = Math.floor(cx / CELL), y0 = Math.floor(cy / CELL); let best = Infinity; for (let y = Math.max(0, y0 - c); y <= Math.min(h - 1, y0 + c); y++) for (let x = Math.max(0, x0 - c); x <= Math.min(w - 1, x0 + c); x++) if (m[y * w + x]) best = Math.min(best, Math.hypot(x - x0, y - y0) * CELL); return best; };
  const suitability = (x, y, s) => {
    const win = SIZE_PRESETS[s.citySize].mapSize / 2;
    if (x < win + 500 || y < win + 500 || x > size - win - 500 || y > size - win - 500) return -Infinity;
    const ci = Math.floor(y / CELL) * w + Math.floor(x / CELL);
    if (T.water[ci] || T.buildability[ci] < 0.6) return -Infinity;
    const land = boxMean(x, y, s.radius * 1.15);
    if (land < 0.55) return -Infinity;
    const wd = waterWithin(x, y, 6000, false);
    return 2.2 * land + (wd < 4500 ? 0.35 * (1 - Math.abs(wd - 1500) / 4500) : 0) + 0.25 * boxMean(x, y, s.radius * 2.2); // room to grow
  };
  const placed = [], relations = [];
  const clearOf = (x, y, s, host, factor) => placed.every((o) => { const need = (s.radius + o.radius) * (o === host ? factor : 1) + (o === host ? 0 : 1200); return Math.hypot(x - o.position.x, y - o.position.y) >= need; });
  // how tightly the region is knit: large regions are metropolitan, small ones a scatter of towns
  const pGlue = P >= 4e6 ? 0.42 : P >= 1.8e6 ? 0.3 : P >= 9e5 ? 0.18 : 0.08, pNear = P >= 1.8e6 ? 0.25 : 0.18;
  for (const s of region.settlements) {
    let best = null, intended = 'SEPARATE', host = null, why;
    if (!placed.length) {
      for (let y = CELL; y < size; y += 3 * CELL) for (let x = CELL; x < size; x += 3 * CELL) {
        const sc = suitability(x, y, s) - 1.4 * Math.hypot(x - size / 2, y - size / 2) / size + rng.range(0, 0.05);
        if (!best || sc > best.sc) best = { x, y, sc };
      }
      why = 'largest_area_of_good_building_land_near_the_middle_of_the_region';
    } else {
      const u = rng.next(), big = s.populationTarget >= 60000;
      intended = big && u < pGlue ? 'GLUED' : u < pGlue + pNear ? 'NEAR_TOUCHING' : 'SEPARATE';
      // a host to settle beside: bigger places attract more, the primary most of all
      let tw = 0; const weights = placed.map((o) => { const v = o.populationTarget ** 0.7 / (1 + 0.6 * o.attached); tw += v; return v; });
      let pickU = rng.next() * tw; host = placed[0];
      for (let k = 0; k < placed.length; k++) { pickU -= weights[k]; if (pickU <= 0) { host = placed[k]; break; } }
      const tryRing = (kind) => {
        const gap = kind === 'GLUED' ? -0.18 * (s.radius + host.radius) : kind === 'NEAR_TOUCHING' ? rng.range(300, 1300) : rng.range(3500, 9000) + 2000 * rng.next();
        const D = s.radius + host.radius + gap, factor = kind === 'GLUED' ? 0.8 : 1;
        let b = null;
        for (let k = 0; k < 40; k++) for (const f of [1, 0.94, 1.07]) {
          const a = (k / 40) * Math.PI * 2, x = Math.round((host.position.x + Math.cos(a) * D * f) / CELL) * CELL, y = Math.round((host.position.y + Math.sin(a) * D * f) / CELL) * CELL;
          if (!clearOf(x, y, s, host, factor)) continue;
          const sc = suitability(x, y, s) + rng.range(0, 0.12);
          if (sc > -Infinity && (!b || sc > b.sc)) b = { x, y, sc };
        }
        return b;
      };
      for (const kind of intended === 'GLUED' ? ['GLUED', 'NEAR_TOUCHING', 'SEPARATE'] : intended === 'NEAR_TOUCHING' ? ['NEAR_TOUCHING', 'SEPARATE'] : ['SEPARATE']) { best = tryRing(kind); if (best) { intended = kind; break; } }
      why = best ? { GLUED: `grown_together_with_${host.name}`, NEAR_TOUCHING: `founded_beside_${host.name}_with_open_land_between`, SEPARATE: `separate_town_in_the_orbit_of_${host.name}` }[intended] : null;
      if (!best) { // anywhere there is room
        host = null; intended = 'SEPARATE';
        for (let y = CELL; y < size; y += 3 * CELL) for (let x = CELL; x < size; x += 3 * CELL) { if (!clearOf(x, y, s, null, 1)) continue; const sc = suitability(x, y, s) + rng.range(0, 0.05); if (sc > -Infinity && (!best || sc > best.sc)) best = { x, y, sc }; }
        why = 'free_standing_site_on_good_land';
      }
    }
    if (!best) { s.unplaced = true; continue; }
    if (host) host.attached++;
    const mapSize = SIZE_PRESETS[s.citySize].mapSize;
    Object.assign(s, {
      position: { x: best.x, y: best.y }, attached: 0, hostId: host ? host.id : null, intendedRelation: intended,
      origin: { x: Math.round((best.x - mapSize / 2) / 50) * 50, y: Math.round((best.y - mapSize / 2) / 50) * 50 }, mapSize,
      foundingBoundary: circlePolygon(best.x, best.y, s.radius, 36), growthBoundary: circlePolygon(best.x, best.y, s.radius * 1.5, 36),
      influenceRadius: Math.round(s.radius * (2.2 + 3 * (s.populationTarget / P))), orientation: rng.range(0, Math.PI),
      reason: why,
    });
    placed.push(s);
  }
  region.settlements = region.settlements.filter((s) => !s.unplaced);
  // roles follow the site
  const used = new Set();
  for (const s of region.settlements) {
    const seaD = waterWithin(s.position.x, s.position.y, s.radius + 2500, true);
    let role = 'MIXED';
    if (s.rank === 1) role = rng.chance(0.3) ? 'ADMINISTRATIVE' : 'MIXED';
    else if (seaD < s.radius + 1500 && !used.has('PORT') && s.populationTarget >= 50000) role = 'PORT';
    else if (seaD < s.radius + 1500 && s.populationTarget < 60000 && rng.chance(0.5)) role = 'RESORT';
    else { const u = rng.next(); role = u < 0.22 ? 'INDUSTRIAL' : u < 0.32 && !used.has('UNIVERSITY') ? 'UNIVERSITY' : u < 0.42 && !used.has('LOGISTICS') ? 'LOGISTICS' : u < 0.45 && !used.has('MILITARY') ? 'MILITARY' : 'MIXED'; }
    used.add(role); s.role = role;
    if (s.scale === 'LOCAL_TOWN' && role !== 'MIXED') s.scale = 'SPECIALIZED_TOWN';
    // each settlement is planned in its own way
    const pool = s.rank === 1 ? ['default', 'radial_formal', 'polycentric', 'centralised'] : role === 'INDUSTRIAL' || role === 'LOGISTICS' ? ['strong_grid', 'default', 'flat_loose'] : role === 'RESORT' ? ['organic', 'flat_loose'] : ['default', 'strong_grid', 'organic', 'radial_formal', 'centralised', 'flat_loose', 'rugged'];
    s.planningProfile = rng.pick(pool);
    s.administrativeId = `adm_${s.id.slice(-2)}`;
    s.reason = `${s.scale.toLowerCase()}_with_${role.toLowerCase()}_role_${s.reason}`;
  }
  // relations between neighbours, and the boundary each pair shares
  const S = region.settlements, parent = S.map((_, i) => i), find = (i) => (parent[i] === i ? i : (parent[i] = find(parent[i])));
  for (let i = 0; i < S.length; i++) for (let j = i + 1; j < S.length; j++) {
    const a = S[i], b = S[j], D = Math.hypot(b.position.x - a.position.x, b.position.y - a.position.y), gap = D - a.radius - b.radius;
    const overlap = Math.abs(a.position.x - b.position.x) < (a.mapSize + b.mapSize) / 2 && Math.abs(a.position.y - b.position.y) < (a.mapSize + b.mapSize) / 2;
    if (gap > 5000 && !overlap) continue;
    const relation = gap < 0 ? 'GLUED' : gap < 1500 ? 'NEAR_TOUCHING' : 'SEPARATE';
    const ux = (b.position.x - a.position.x) / D, uy = (b.position.y - a.position.y) / D, t = a.radius + gap / 2; // boundary: midway across the gap (or the overlap)
    const seam = { x: a.position.x + ux * t, y: a.position.y + uy * t, nx: ux, ny: uy };
    relations.push({ id: `relation_${a.id.slice(-2)}_${b.id.slice(-2)}`, type: 'settlement_relation', createdByStage: 'sites', a: a.id, b: b.id, relation, gap: Math.round(gap), distance: Math.round(D), seam, windowsOverlap: overlap, reason: relation === 'GLUED' ? 'the_two_founding_areas_overlap_so_their_fabrics_meet_at_a_shared_boundary' : relation === 'NEAR_TOUCHING' ? 'founding_areas_come_within_1500_m_of_each_other' : 'clearly_separate_settlements' });
    if (relation === 'GLUED') parent[find(i)] = find(j);
  }
  const groups = new Map();
  S.forEach((s, i) => { const g = find(i); (groups.get(g) || groups.set(g, []).get(g)).push(s); });
  let gi = 0;
  for (const members of groups.values()) {
    const id = `continuity_${String(++gi).padStart(2, '0')}`, kind = members.length >= 3 ? 'CONTINUOUS_METROPOLITAN' : members.length === 2 ? 'GLUED' : 'FREE_STANDING';
    for (const s of members) { s.urbanContinuityGroup = id; s.continuity = kind; s.metroRegionId = Math.hypot(s.position.x - S[0].position.x, s.position.y - S[0].position.y) <= S[0].influenceRadius + s.radius ? 'metro_01' : null; }
  }
  for (const r of relations) if (r.relation === 'GLUED' && S.find((s) => s.id === r.a).continuity === 'CONTINUOUS_METROPOLITAN') r.partOf = 'CONTINUOUS_METROPOLITAN';
  region.relations = relations;
  log(`${S.length} sites; relations: ${['GLUED', 'NEAR_TOUCHING', 'SEPARATE'].map((k) => `${relations.filter((r) => r.relation === k).length} ${k.toLowerCase()}`).join(', ')}; ${[...groups.values()].filter((m) => m.length > 1).length} continuous urban group(s), largest ${Math.max(...[...groups.values()].map((m) => m.length))} settlements; roles: ${S.map((s) => s.role).filter((r) => r !== 'MIXED').join(', ').toLowerCase() || 'all mixed'}`);
}

// ---------------------------------------------------------------- 4. regional infrastructure
function planInfrastructure(region, rng, log) {
  const T = region.terrain, { w, h, n, size } = T, S = region.settlements;
  const cellOf = (p) => clamp(Math.floor(p.y / CELL), 0, h - 1) * w + clamp(Math.floor(p.x / CELL), 0, w - 1);
  const centre = (c) => ({ x: ((c % w) + 0.5) * CELL, y: (Math.floor(c / w) + 0.5) * CELL });
  const owner = new Int16Array(n).fill(-1); // which settlement's founding area a cell lies in
  S.forEach((s, k) => { const c = Math.ceil(s.radius / CELL), x0 = Math.floor(s.position.x / CELL), y0 = Math.floor(s.position.y / CELL); for (let y = Math.max(0, y0 - c); y <= Math.min(h - 1, y0 + c); y++) for (let x = Math.max(0, x0 - c); x <= Math.min(w - 1, x0 + c); x++) if (Math.hypot(x - x0, y - y0) * CELL <= s.radius) owner[y * w + x] = k; });
  const dl = NEIGH16.map(([dx, dy]) => Math.hypot(dx, dy)), dx_ = NEIGH16.map(([dx], k) => dx / dl[k]), dy_ = NEIGH16.map(([, dy], k) => dy / dl[k]);
  const used = { road: new Uint8Array(n), rail: new Uint8Array(n) };
  const route = (from, to, kind, skip) => {
    const gx = to % w, gy = Math.floor(to / w), rail = kind === 'rail';
    const path = leastCostPath({
      w, h, start: from, goal: to, neighbours: NEIGH16,
      stepCost: (a, b, k, arrival) => {
        if (T.sea[b]) return Infinity;
        let c = dl[k] * CELL * (1 + (rail ? 60 : 22) * T.slope[b]);
        if (T.water[b]) c *= 6; // a river crossing
        if (owner[b] >= 0 && !skip.includes(owner[b])) c *= 3.2; // keep out of a third settlement: pass it by
        if (used[kind][b]) c *= 0.5;
        if (arrival >= 0) { const dot = dx_[k] * dx_[arrival] + dy_[k] * dy_[arrival]; c += (1 - dot) * (rail ? 9 : 2) * CELL + (rail && dot < 0.7 ? 6000 : 0); }
        return c;
      },
      heuristic: (i) => 0.6 * CELL * Math.hypot((i % w) - gx, Math.floor(i / w) - gy),
    });
    if (!path) return null;
    for (const c of path.cells) used[kind][c] = 1;
    const pts = simplifyDP(path.cells.map(centre), CELL * 0.9);
    const fit = pts.length > 2 ? fitAlignment(pts, { minRadius: rail ? 1500 : 500, step: 200, maxShift: rail ? 900 : 450 }) : { points: pts };
    return fit.points;
  };
  // exits from the region: where the inland edges are open land
  const exits = [];
  for (const [ex, ey, name] of [[0.5, 0.02, 'north'], [0.98, 0.5, 'east'], [0.5, 0.98, 'south'], [0.02, 0.5, 'west']]) {
    let best = null;
    for (let t = -0.3; t <= 0.3; t += 0.05) { const p = { x: (ex + (ex === 0.5 ? t : 0)) * size, y: (ey + (ey === 0.5 ? t : 0)) * size }, c = cellOf(p); if (!T.water[c] && T.buildability[c] > 0.5 && (!best || Math.abs(t) < Math.abs(best.t))) best = { ...p, t, name }; }
    if (best) exits.push(best);
  }
  const prim = S[0];
  exits.sort((a, b) => Math.hypot(a.x - prim.position.x, a.y - prim.position.y) - Math.hypot(b.x - prim.position.x, b.y - prim.position.y));
  const dist2 = (a, b) => Math.hypot(a.position.x - b.position.x, a.position.y - b.position.y);

  // --- roads: a tree that reaches every settlement, plus direct links between the big ones
  const links = [], inTree = [0];
  while (inTree.length < S.length) {
    let best = null;
    for (const i of inTree) for (let j = 0; j < S.length; j++) { if (inTree.includes(j)) continue; const d = dist2(S[i], S[j]) / (S[i].populationTarget ** 0.15); if (!best || d < best.d) best = { d, i, j }; }
    links.push([best.i, best.j, 'network_tree']); inTree.push(best.j);
  }
  for (let j = 1; j < S.length; j++) if (S[j].populationTarget >= 150000 && !links.some((l) => (l[0] === 0 && l[1] === j) || (l[1] === 0 && l[0] === j))) links.push([0, j, 'direct_link_between_major_cities']);
  const roads = [];
  const settleById = new Map(S.map((s) => [s.id, s]));
  for (const s of S) { s.gateways = []; s.railEntries = []; s.throughPairs = []; }
  const relationOf = (a, b) => region.relations.find((r) => (r.a === a.id && r.b === b.id) || (r.a === b.id && r.b === a.id));
  // where a line leaves a settlement's window (walking away from its centre)
  const exitPoint = (pts, s, fromStart) => {
    const seq = fromStart ? pts : [...pts].reverse(), half = s.mapSize / 2 - 200, inside = (p) => Math.abs(p.x - s.position.x) < half && Math.abs(p.y - s.position.y) < half;
    for (let i = 1; i < seq.length; i++) if (inside(seq[i - 1]) && !inside(seq[i])) {
      let a = seq[i - 1], b = seq[i];
      for (let k = 0; k < 12; k++) { const m = { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }; if (inside(m)) a = m; else b = m; }
      return { point: a, index: fromStart ? i : seq.length - 1 - i };
    }
    return null;
  };
  const seamPoint = (pts, rel) => { // where a line crosses the boundary between two neighbours
    for (let i = 1; i < pts.length; i++) { const d0 = (pts[i - 1].x - rel.seam.x) * rel.seam.nx + (pts[i - 1].y - rel.seam.y) * rel.seam.ny, d1 = (pts[i].x - rel.seam.x) * rel.seam.nx + (pts[i].y - rel.seam.y) * rel.seam.ny; if (d0 * d1 <= 0 && d0 !== d1) { const t = d0 / (d0 - d1); return { x: pts[i - 1].x + (pts[i].x - pts[i - 1].x) * t, y: pts[i - 1].y + (pts[i].y - pts[i - 1].y) * t }; } }
    return { x: rel.seam.x, y: rel.seam.y };
  };
  const local = (s, p) => ({ x: p.x - s.origin.x, y: p.y - s.origin.y });
  let rid = 0;
  const addRoad = (a, b, exit, why) => {
    const pts = route(cellOf(a.position), b ? cellOf(b.position) : cellOf(exit), 'road', b ? [S.indexOf(a), S.indexOf(b)] : [S.indexOf(a)]);
    if (!pts || pts.length < 2) return;
    const id = `regroad_${String(++rid).padStart(2, '0')}`, rel = b ? relationOf(a, b) : null;
    const cls = !b || Math.min(a.populationTarget, b.populationTarget) >= 120000 ? 'REGIONAL_HIGHWAY' : 'INTERCITY_ROAD';
    let geometry = pts, seam = null;
    if (rel && rel.windowsOverlap && rel.relation !== 'SEPARATE') { // neighbours: the road is handed over at their shared boundary
      seam = seamPoint(pts, rel);
      a.gateways.push({ ...local(a, seam), regionalRoadId: id, towards: b.name, seam: true });
      b.gateways.push({ ...local(b, seam), regionalRoadId: id, towards: a.name, seam: true });
      geometry = [seam];
    } else {
      const ea = exitPoint(pts, a, true), eb = b ? exitPoint(pts, b, false) : null;
      if (ea) a.gateways.push({ ...local(a, ea.point), regionalRoadId: id, towards: b ? b.name : `the ${exit.name}` });
      if (eb) b.gateways.push({ ...local(b, eb.point), regionalRoadId: id, towards: a.name });
      geometry = pts.slice(ea ? ea.index : 0, eb ? eb.index + 1 : pts.length);
      if (ea) geometry.unshift(ea.point);
      if (eb) geometry.push(eb.point);
    }
    // a settlement the road runs through on its way: an explicit decision, taken later by that settlement's own plan
    const through = [];
    for (const c of S) {
      if (c === a || c === b) continue;
      let nearest = Infinity; for (const p of pts) nearest = Math.min(nearest, Math.hypot(p.x - c.position.x, p.y - c.position.y));
      if (nearest > c.radius * 1.15) continue;
      const half = c.mapSize / 2 - 200, inside = (p) => Math.abs(p.x - c.position.x) < half && Math.abs(p.y - c.position.y) < half;
      let first = null, last = null;
      for (let i = 1; i < pts.length; i++) { if (!inside(pts[i - 1]) && inside(pts[i]) && !first) first = pts[i]; if (inside(pts[i - 1]) && !inside(pts[i])) last = pts[i - 1]; }
      if (first && last) { c.gateways.push({ ...local(c, first), regionalRoadId: id, towards: a.name }, { ...local(c, last), regionalRoadId: id, towards: b ? b.name : `the ${exit.name}` }); c.throughPairs.push([id, id]); through.push(c.id); }
    }
    roads.push({ id, type: cls, createdByStage: 'infrastructure', reason: `${why}_${a.name.toLowerCase()}_to_${b ? b.name.toLowerCase() : 'beyond_the_region_' + exit.name}`, system: cls === 'REGIONAL_HIGHWAY' ? 'LIMITED_ACCESS' : 'STREET', from: a.id, to: b ? b.id : null, exit: b ? null : exit.name, points: geometry, routed: pts, length: polylineLength(geometry), handedOverAtSeam: !!seam, passesThrough: through });
  };
  for (const [i, j, why] of links) addRoad(S[i], S[j], null, why);
  for (const ex of exits.slice(0, S.length > 4 ? 3 : 2)) addRoad(prim, null, ex, 'road_out_of_the_region_from');
  region.regionalRoads = roads;

  // --- rail: one main line through the largest cities, branches to the others that warrant it
  const railS = S.filter((s) => s.populationTarget >= 60000 || ['PORT', 'INDUSTRIAL', 'LOGISTICS'].includes(s.role));
  for (const s of S) s.rail = railS.includes(s);
  const lines = [];
  let lid = 0;
  const addRail = (a, b, exit, cls, why) => {
    const pts = route(cellOf(a.position), b ? cellOf(b.position) : cellOf(exit), 'rail', b ? [S.indexOf(a), S.indexOf(b)] : [S.indexOf(a)]);
    if (!pts || pts.length < 2) return;
    const id = `regrail_${String(++lid).padStart(2, '0')}`, rel = b ? relationOf(a, b) : null;
    let geometry, seam = null;
    if (rel && rel.windowsOverlap && rel.relation !== 'SEPARATE') { // neighbours: the line passes from one to the other at their boundary
      seam = seamPoint(pts, rel);
      a.railEntries.push({ ...local(a, seam), regionalRailId: id, seam: true });
      b.railEntries.push({ ...local(b, seam), regionalRailId: id, seam: true });
      geometry = [seam, seam];
    } else {
      const ea = exitPoint(pts, a, true), eb = b ? exitPoint(pts, b, false) : null;
      if (ea) a.railEntries.push({ ...local(a, ea.point), regionalRailId: id });
      if (eb) b.railEntries.push({ ...local(b, eb.point), regionalRailId: id });
      geometry = pts.slice(ea ? ea.index : 0, eb ? eb.index + 1 : pts.length);
      if (ea) geometry.unshift(ea.point);
      if (eb) geometry.push(eb.point);
      if (geometry.length < 2) geometry = [ea ? ea.point : pts[0], eb ? eb.point : pts[pts.length - 1]];
    }
    lines.push({ id, type: cls, createdByStage: 'infrastructure', reason: `${why}_${a.name.toLowerCase()}_${b ? b.name.toLowerCase() : 'beyond_the_region_' + exit.name}`, system: 'RAIL', profile: cls, from: a.id, to: b ? b.id : null, exit: b ? null : exit.name, points: geometry, length: polylineLength(geometry), handedOverAtSeam: !!seam });
  };
  if (railS.length) {
    const main = railS.filter((s) => s.populationTarget >= 150000 || s === prim);
    // order the main-line cities along the region's long axis through the primary city
    const ax = exits.length ? Math.atan2(exits[0].y - prim.position.y, exits[0].x - prim.position.x) : 0, proj = (s) => (s.position.x - prim.position.x) * Math.cos(ax) + (s.position.y - prim.position.y) * Math.sin(ax);
    main.sort((p, q) => proj(p) - proj(q));
    for (let i = 0; i + 1 < main.length; i++) addRail(main[i], main[i + 1], null, 'INTERCITY_RAIL', 'main_line_between');
    const far = exits.slice().sort((a, b) => ((b.x - prim.position.x) * Math.cos(ax) + (b.y - prim.position.y) * Math.sin(ax)) - ((a.x - prim.position.x) * Math.cos(ax) + (a.y - prim.position.y) * Math.sin(ax)));
    if (far.length) addRail(main[main.length - 1], null, far[0], 'INTERCITY_RAIL', 'main_line_out_of_the_region_from');
    if (far.length > 1) addRail(main[0], null, far[far.length - 1], 'INTERCITY_RAIL', 'main_line_out_of_the_region_from');
    for (const s of railS) {
      if (main.includes(s)) continue;
      const hub = main.slice().sort((p, q) => dist2(p, s) - dist2(q, s))[0];
      const freight = ['PORT', 'INDUSTRIAL', 'LOGISTICS'].includes(s.role) && s.populationTarget < 60000;
      addRail(s, hub, null, freight ? 'FREIGHT_RAIL' : 'REGIONAL_RAIL', freight ? 'freight_corridor_between' : 'regional_branch_between');
    }
  }
  region.regionalRail = lines;

  // --- regional anchors and protected land
  const anchors = [];
  for (const s of S) if (s.role === 'PORT') anchors.push({ id: `reganchor_port_${s.id.slice(-2)}`, type: 'PORT', createdByStage: 'infrastructure', reason: `sea_port_of_${s.name.toLowerCase()}`, settlementId: s.id, position: s.position });
  if (region.regionalPopulationTarget >= 1500000) {
    let best = null;
    for (let y = 10; y < h - 10; y += 3) for (let x = 10; x < w - 10; x += 3) {
      const p = { x: (x + 0.5) * CELL, y: (y + 0.5) * CELL }, d = Math.hypot(p.x - prim.position.x, p.y - prim.position.y), i = y * w + x;
      if (d < prim.radius + 4000 || d > prim.radius + 16000 || T.buildability[i] < 0.9 || T.water[i] || S.some((s) => Math.hypot(p.x - s.position.x, p.y - s.position.y) < s.radius + 2000)) continue;
      let flat = 0; for (let yy = y - 6; yy <= y + 6; yy++) for (let xx = x - 6; xx <= x + 6; xx++) flat += T.buildability[yy * w + xx] > 0.85 && !T.water[yy * w + xx] ? 1 : 0;
      const sc = flat / 169 - d / 60000 + (used.road[i] ? 0.2 : 0);
      if (!best || sc > best.sc) best = { sc, p };
    }
    if (best) anchors.push({ id: 'reganchor_airport', type: 'AIRPORT', createdByStage: 'infrastructure', reason: `flat_open_site_${Math.round(Math.hypot(best.p.x - prim.position.x, best.p.y - prim.position.y) / 1000)}_km_from_${prim.name.toLowerCase()}_clear_of_every_settlement`, position: best.p });
  }
  region.regionalAnchors = anchors;
  const prot = [];
  { const mask = new Uint8Array(n); for (let i = 0; i < n; i++) mask[i] = !T.water[i] && T.slope[i] > 0.085 ? 1 : 0;
    const comps = labelComponents(mask, w, h);
    comps.sizes.forEach((sz, l) => { if (sz * CELL * CELL < 6e6) return; const rings = traceRegionRings(comps.labels, w, h, CELL, l); if (rings.length) prot.push({ id: `protected_${String(prot.length + 1).padStart(2, '0')}`, type: 'UPLAND_RESERVE', createdByStage: 'infrastructure', reason: 'steep_upland_kept_as_open_landscape', polygon: rings[0], areaKm2: (sz * CELL * CELL) / 1e6 }); }); }
  T.rivers.forEach((r, k) => prot.push({ id: `protected_river_${k + 1}`, type: 'RIVER_CORRIDOR', createdByStage: 'infrastructure', reason: 'river_and_its_floodplain_kept_as_a_green_corridor', points: r.points, width: r.width + 900 }));
  region.protectedAreas = prot;
  log(`${roads.length} regional roads (${roads.filter((r) => r.type === 'REGIONAL_HIGHWAY').length} highways, ${roads.filter((r) => r.handedOverAtSeam).length} handed over at a shared boundary, ${roads.filter((r) => r.passesThrough.length).length} passing through a settlement), ${lines.length} rail lines (${lines.filter((l) => l.type === 'INTERCITY_RAIL').length} main line sections), ${S.filter((s) => !s.rail).length} settlements without rail, ${anchors.length} regional anchors, ${prot.length} protected areas`);
}

// ---------------------------------------------------------------- 5. interface zones
function planInterfaces(region, rng, log) {
  const S = new Map(region.settlements.map((s) => [s.id, s])), zones = [];
  for (const rel of region.relations) {
    if (rel.gap > 4000) continue;
    const a = S.get(rel.a), b = S.get(rel.b), tx = -rel.seam.ny, ty = rel.seam.nx;
    const halfLen = Math.min(a.radius, b.radius) * 0.95, halfWid = Math.max(260, rel.gap / 2 + 180);
    const corner = (u, v) => ({ x: rel.seam.x + tx * u + rel.seam.nx * v, y: rel.seam.y + ty * u + rel.seam.ny * v });
    const polygon = [corner(-halfLen, -halfWid), corner(halfLen, -halfWid), corner(halfLen, halfWid), corner(-halfLen, halfWid)];
    const near = (line) => line.points.some((p) => Math.abs((p.x - rel.seam.x) * tx + (p.y - rel.seam.y) * ty) < halfLen && Math.abs((p.x - rel.seam.x) * rel.seam.nx + (p.y - rel.seam.y) * rel.seam.ny) < halfWid + 300);
    const rail = region.regionalRail.some(near), highway = region.regionalRoads.some((r) => r.type === 'REGIONAL_HIGHWAY' && !(r.from === a.id && r.to === b.id) && !(r.from === b.id && r.to === a.id) && near(r));
    const linked = region.regionalRoads.some((r) => (r.from === a.id && r.to === b.id) || (r.from === b.id && r.to === a.id));
    const T = region.terrain, ci = Math.max(0, Math.min(T.n - 1, Math.floor(rel.seam.y / CELL) * T.w + Math.floor(rel.seam.x / CELL))), wet = T.water[ci] || T.slope[ci] > 0.07;
    const industrial = [a.role, b.role].some((r) => r === 'INDUSTRIAL' || r === 'LOGISTICS' || r === 'MILITARY');
    let type, why;
    if (highway) [type, why] = ['HARD_INFRASTRUCTURE_EDGE', 'a_regional_highway_runs_between_the_two_settlements'];
    else if (wet) [type, why] = ['GREEN_WEDGE', 'water_or_steep_ground_keeps_the_two_apart'];
    else if (rail && rel.relation !== 'GLUED') [type, why] = ['TRANSPORT_CORRIDOR', 'the_railway_occupies_the_land_between_them'];
    else if (industrial) [type, why] = ['INDUSTRIAL_BUFFER', 'industry_and_yards_of_one_settlement_face_the_other'];
    else if (rel.relation === 'GLUED') [type, why] = linked ? ['COMMERCIAL_CORRIDOR', 'the_road_between_the_two_centres_became_a_commercial_spine_across_the_boundary'] : ['URBAN_INFILL', 'the_two_fabrics_have_grown_into_each_other'];
    else [type, why] = rng.chance(0.5) ? ['GREEN_WEDGE', 'planning_policy_keeps_the_gap_open'] : ['MIXED_EDGE', 'scattered_edge_uses_between_two_towns'];
    zones.push({ id: `interface_${String(zones.length + 1).padStart(2, '0')}`, type, createdByStage: 'interfaces', reason: why, a: a.id, b: b.id, relation: rel.partOf || rel.relation, gap: rel.gap, polygon, seamLine: [corner(-halfLen, 0), corner(halfLen, 0)], preserveSeam: true, streetGridsBlended: false, position: { x: rel.seam.x, y: rel.seam.y } });
  }
  region.interfaceZones = zones;
  log(`${zones.length} interface zones: ${INTERFACE_TYPES.map((t) => [t, zones.filter((z) => z.type === t).length]).filter(([, c]) => c).map(([t, c]) => `${c} ${t.toLowerCase()}`).join(', ') || 'none'}`);
}

// ---------------------------------------------------------------- 6. settlements
export function settlementConfig(region, s) {
  const T = region.terrain, mapSize = s.mapSize, N = Math.round(mapSize / 50);
  const data = new Float32Array(N * N);
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) data[y * N + x] = T.elevationAt(s.origin.x + (x + 0.5) * 50, s.origin.y + (y + 0.5) * 50);
  const [lo, hi] = SIZE_PRESETS[s.citySize].popRange;
  // land on the far side of a boundary shared with a neighbour is not this settlement's
  const exclusions = [];
  for (const rel of region.relations) {
    if (!rel.windowsOverlap) continue;
    const mine = rel.a === s.id, other = rel.b === s.id;
    if (!mine && !other) continue;
    const sign = mine ? 1 : -1;
    exclusions.push({ x: rel.seam.x - s.origin.x, y: rel.seam.y - s.origin.y, nx: rel.seam.nx * sign, ny: rel.seam.ny * sign, neighbour: mine ? rel.b : rel.a });
  }
  return {
    ...DEFAULT_CONFIG, ...PLANNING_PROFILES[s.planningProfile],
    seed: `${region.seed}/${s.id}`, citySize: s.citySize, targetPopulation: clamp(s.populationTarget, lo, hi),
    heightmap: { width: N, height: N, data, metres: true },
    bypass: s.throughPairs.length ? 'always' : 'auto',
    regionalContext: { regionSeed: region.seed, settlementId: s.id, role: s.role, scale: s.scale, exclusions, gateways: s.gateways, railEntries: s.rail ? s.railEntries : [], rail: s.rail && s.railEntries.length > 0, railApproaches: s.railEntries.length, throughPairs: s.throughPairs },
  };
}

function finishSettlement(region, s) {
  const m = s.model, live = m.network.edges.filter((e) => !e.removed && e.cls !== 'rail');
  s.modelledPopulation = m.brief.population;
  s.capacityLimited = m.brief.population < s.populationTarget * 0.95;
  s.summary = {
    areaKm2: m.districts.reduce((a, d) => a + d.area, 0) / 1e6, streetKm: live.reduce((a, e) => a + e.len, 0) / 1000,
    districts: m.districts.length, hasStation: !!(m.rail && m.rail.stationComplex), stationTracks: m.rail?.stationComplex?.platformTracks ?? 0, stationConfiguration: m.rail?.stationComplex?.configuration ?? null,
    railLines: m.rail ? m.rail.lines.length : 0, corridors: m.corridors.length, civicAxisAngle: m.civicComposition.axisAngle,
    regionalRoadDecisions: m.regionalRoadDecisions.map((d) => d.behaviour), warnings: m.validation.warnings.length,
  };
  // stitch: regional lines end exactly where the settlement's own roads and tracks begin
  for (const a of m.anchors) {
    if (!a.regionalRoadId) continue;
    const road = region.regionalRoads.find((r) => r.id === a.regionalRoadId), p = { x: a.position.x + s.origin.x, y: a.position.y + s.origin.y };
    if (!road) continue;
    if (road.handedOverAtSeam) { (road.seamEnds = road.seamEnds || []).push(p); continue; }
    const d0 = Math.hypot(road.points[0].x - p.x, road.points[0].y - p.y), d1 = Math.hypot(road.points[road.points.length - 1].x - p.x, road.points[road.points.length - 1].y - p.y);
    if (Math.min(d0, d1) < 6000 && !road.passesThrough.includes(s.id)) { if (d0 < d1) road.points[0] = p; else road.points[road.points.length - 1] = p; }
  }
  for (const pt of m.rail?.portals || []) {
    if (!pt.regionalRailId) continue;
    const line = region.regionalRail.find((l) => l.id === pt.regionalRailId), p = { x: pt.x + s.origin.x, y: pt.y + s.origin.y };
    if (!line) continue;
    const d0 = Math.hypot(line.points[0].x - p.x, line.points[0].y - p.y), d1 = Math.hypot(line.points[line.points.length - 1].x - p.x, line.points[line.points.length - 1].y - p.y);
    if (line.handedOverAtSeam) { line.points[line.points[0].set ? 1 : 0] = { ...p, set: true }; continue; }
    if (Math.min(d0, d1) < 4000) { if (d0 < d1) line.points[0] = p; else line.points[line.points.length - 1] = p; }
  }
}

function finishRegion(region) {
  for (const r of region.regionalRoads) { if (r.seamEnds && r.seamEnds.length >= 2) r.points = r.seamEnds.slice(0, 2); r.length = polylineLength(r.points); }
  for (const l of region.regionalRail) l.length = polylineLength(l.points);
  const S = region.settlements, by = (k) => S.reduce((o, s) => { o[s[k]] = (o[s[k]] || 0) + 1; return o; }, {});
  region.stats = {
    regionalPopulationTarget: region.regionalPopulationTarget, allocatedPopulation: S.reduce((a, s) => a + s.populationTarget, 0), modelledPopulation: S.reduce((a, s) => a + (s.modelledPopulation || 0), 0),
    settlements: S.length, byScale: by('scale'), byRole: by('role'), byCentreStrength: by('centreStrength'),
    relations: region.relations.reduce((o, r) => { o[r.relation] = (o[r.relation] || 0) + 1; return o; }, {}),
    continuousGroups: [...new Set(S.filter((s) => s.continuity !== 'FREE_STANDING').map((s) => s.urbanContinuityGroup))].length,
    largestContinuousGroup: Math.max(...Object.values(S.reduce((o, s) => { o[s.urbanContinuityGroup] = (o[s.urbanContinuityGroup] || 0) + 1; return o; }, {}))),
    regionalRoadKm: region.regionalRoads.reduce((a, r) => a + r.length, 0) / 1000, regionalRailKm: region.regionalRail.reduce((a, l) => a + l.length, 0) / 1000,
    streetKm: S.reduce((a, s) => a + (s.summary?.streetKm || 0), 0), urbanAreaKm2: S.reduce((a, s) => a + (s.summary?.areaKm2 || 0), 0),
    stations: S.filter((s) => s.summary?.hasStation).length, interfaceZones: region.interfaceZones.length,
  };
}

const STAGES = [['terrain', planRegionTerrain], ['regionalPlan', planSettlementSystem], ['sites', planSites], ['infrastructure', planInfrastructure], ['interfaces', planInterfaces]];
function planRegion(region) {
  for (const [id, fn] of STAGES) {
    const t0 = performance.now(), messages = [];
    fn(region, new SeededRandom(region.seed).fork('region/' + id), (msg) => messages.push(msg));
    region.metadata.log.push({ stage: id, ms: performance.now() - t0, messages });
  }
}

// Everything up to and including the settlements, synchronously (tests, scripts).
export function generateRegionSync(input, { settlements = true } = {}) {
  const region = createRegionModel(input);
  planRegion(region);
  if (settlements) for (const s of region.settlements) { s.model = createCityModel(settlementConfig(region, s)); runPipelineSync(s.model); finishSettlement(region, s); }
  finishRegion(region);
  return region;
}

// The same, yielding between settlements so a UI can show progress.
export async function generateRegion(input, onProgress = null) {
  const region = createRegionModel(input);
  planRegion(region);
  let k = 0;
  for (const s of region.settlements) {
    if (onProgress) await onProgress(region, s, ++k);
    s.model = createCityModel(settlementConfig(region, s));
    await runPipeline(s.model, 'terrain', null);
    finishSettlement(region, s);
  }
  finishRegion(region);
  return region;
}
