// REGIONGEN. A region is several settlements, each generated by the ordinary CityGen pipeline,
// placed on one regional terrain and tied together by infrastructure that is planned BEFORE any
// settlement's own fabric exists.
//
//   1. regional terrain            one elevation function for the whole region
//   2. regional plan               how the population is shared out: scales and roles
//   3. settlement sites            where each one goes, and how it relates to its neighbours
//   4. regional infrastructure     intercity roads and highways, regional rail, protected land
//   5. interface zones             what the land between neighbouring settlements becomes
//   6. settlements                 CityGen, once per settlement, with the regional context
//   7. stitching and statistics    regional lines meet the settlements' own gateways and portals
//
// Nothing of CityGen is duplicated: a settlement is a CityModel. Settlements are never merged,
// even when their fabrics touch; each keeps its administrative identity, centre and street grid.

import { seamModeOf, stitchSeams, SEAM_MODES } from './SeamStitcher.js';
import { SeededRandom, makeNoise2D, fbm } from '../core/SeededRandom.js';
import { DEFAULT_CONFIG, SIZE_PRESETS, createCityModel, record } from '../core/CityModel.js';
import { runPipelineSync, runPipeline } from '../core/Pipeline.js';
import { leastCostPath, NEIGH16 } from '../algorithms/LeastCostPath.js';
import { fitAlignment } from '../algorithms/Alignment.js';
import { simplifyDP, polylineLength, pointSegment, circlePolygon } from '../core/Geometry.js';
import { labelComponents } from '../core/Raster.js';
import { traceRegionRings } from '../algorithms/PolygonUtils.js';
import { PLANNING_PROFILES } from './PlanningProfiles.js';

export const SETTLEMENT_SCALES = ['PRIMARY_CITY', 'MAJOR_CITY', 'SECONDARY_CITY', 'SMALL_CITY', 'SPECIALIZED_TOWN', 'LOCAL_TOWN'];
export const SETTLEMENT_ROLES = ['MIXED', 'INDUSTRIAL', 'PORT', 'UNIVERSITY', 'ADMINISTRATIVE', 'LOGISTICS', 'RESORT', 'MILITARY'];
export const INTERFACE_TYPES = ['URBAN_INFILL', 'COMMERCIAL_CORRIDOR', 'INDUSTRIAL_BUFFER', 'GREEN_WEDGE', 'TRANSPORT_CORRIDOR', 'MIXED_EDGE', 'HARD_INFRASTRUCTURE_EDGE'];
export const RELATIONS = ['SEPARATE', 'NEAR_TOUCHING', 'GLUED', 'CONTINUOUS_METROPOLITAN'];
// How the regional population is shared out. `share` is the primary city's part of the whole,
// `alpha` the rank-size exponent of the cities below it, `twin` a second city nearly as large.
export const POPULATION_PROFILES = {
  DOMINANT_CORE: { share: [0.36, 0.48], alpha: 1.3, ranked: 0.86 },
  MONOCENTRIC: { share: [0.52, 0.64], alpha: 1.7, ranked: 0.84 },
  POLYCENTRIC: { share: [0.17, 0.24], alpha: 0.65, ranked: 0.92 },
  TWIN_CORE: { share: [0.27, 0.34], alpha: 1.3, ranked: 0.86, twin: [0.72, 0.93] },
  LINEAR_CORRIDOR: { share: [0.3, 0.4], alpha: 1.05, ranked: 0.88 },
};
const LEGACY_STRUCTURE = { dominant: 'DOMINANT_CORE', balanced: 'DOMINANT_CORE', polycentric: 'POLYCENTRIC' };
const MAX_SETTLEMENTS = 26;
export const DEFAULT_REGION_CONFIG = { seed: 'region-1', regionalPopulationTarget: 1000000, structure: 'auto', coast: 'auto', roadIntensity: 'normal', railIntensity: 'normal' };

const CELL = 250; // regional raster cell (m)
const DENSITY = 9100; // people per km2 of urban land, as in the city brief
const radiusFor = (pop) => Math.sqrt(pop / DENSITY / Math.PI) * 1000;
const sizeFor = (pop) => (pop > SIZE_PRESETS.metropolis.popRange[1] ? 'megacity' : pop > 700000 ? 'metropolis' : pop >= 250000 ? 'major' : pop >= 80000 ? 'medium' : 'small');
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const smooth = (a, b, x) => { const t = clamp((x - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); };

export function createRegionModel(input = {}) {
  const config = { ...DEFAULT_REGION_CONFIG, ...input };
  config.regionalPopulationTarget = clamp(Math.round(Number(config.regionalPopulationTarget) || 1e6), 300000, 12000000);
  return {
    seed: config.seed, config,
    regionalPopulationTarget: config.regionalPopulationTarget,
    terrain: null, regionalPlan: null,
    settlements: [], regionalRoads: [], regionalRail: [], regionalAnchors: [],
    interfaceZones: [], protectedAreas: [], relations: [],
    stats: {}, metadata: { log: [], timings: {} },
  };
}

// ---------------------------------------------------------------- 1. terrain
function planRegionTerrain(region, rng, log) {
  const P = region.regionalPopulationTarget;
  const size = Math.round(clamp(18000 + 26000 * Math.sqrt(P / 1e6), 34000, 104000) / 1000) * 1000;
  const w = Math.round(size / CELL), h = w, n = w * h;
  const noise = makeNoise2D(rng.int(1e9)), noise2 = makeNoise2D(rng.int(1e9));
  const coastal = region.config.coast === 'auto' ? rng.chance(0.7) : region.config.coast === 'yes';
  const seaAngle = rng.range(0, Math.PI * 2), sx = Math.cos(seaAngle), sy = Math.sin(seaAngle);
  const hillAngle = seaAngle + Math.PI + rng.range(-0.8, 0.8), hx = Math.cos(hillAngle), hy = Math.sin(hillAngle);
  const half = size / 2;
  // rivers: from the inland side towards the sea (or across the region), meandering
  const rivers = [];
  const count = rng.chance(0.55) ? 1 : 2;
  for (let k = 0; k < count; k++) {
    const a0 = seaAngle + Math.PI + rng.range(-0.9, 0.9), a1 = seaAngle + rng.range(-0.7, 0.7);
    const p0 = { x: half + Math.cos(a0) * half * 1.3, y: half + Math.sin(a0) * half * 1.3 }, p1 = { x: half + Math.cos(a1) * half * 1.3, y: half + Math.sin(a1) * half * 1.3 };
    const len = Math.hypot(p1.x - p0.x, p1.y - p0.y), nx = -(p1.y - p0.y) / len, ny = (p1.x - p0.x) / len, ph = rng.range(0, 6), amp = rng.range(0.05, 0.12) * len;
    const pts = [];
    for (let t = 0; t <= 1.0001; t += 1 / 80) { const off = amp * (Math.sin(t * 5.3 + ph) * 0.6 + Math.sin(t * 11.7 + ph * 2) * 0.3 + noise2(t * 6, k * 9.1) * 0.5); pts.push({ x: p0.x + (p1.x - p0.x) * t + nx * off, y: p0.y + (p1.y - p0.y) * t + ny * off }); }
    rivers.push({ points: pts, width: 260 - 60 * k });
  }
  // base elevation on the coarse grid (m)
  const base = new Float32Array(n);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const px = (x + 0.5) * CELL, py = (y + 0.5) * CELL, u = (px - half) / half, v = (py - half) / half;
    let e = 22 + 70 * Math.max(0, fbm(noise, px / 16000, py / 16000, 4) + 0.1);
    const inland = u * hx + v * hy;
    e += 300 * smooth(0.35, 1.05, inland + 0.25 * fbm(noise2, px / 9000, py / 9000, 3)); // an upland flank
    if (coastal) { const s = u * sx + v * sy + 0.16 * fbm(noise2, px / 12000 + 7, py / 12000, 3); if (s > 0.5) e = Math.min(e, 6) - (s - 0.5) * 160 - 1.5; else e += 0; }
    base[y * w + x] = e;
  }
  const riverNear = new Uint8Array(n);
  const riverDist = (px, py) => { let d = Infinity, wd = 0; for (const r of rivers) for (let i = 0; i + 1 < r.points.length; i++) { const ps = pointSegment(px, py, r.points[i].x, r.points[i].y, r.points[i + 1].x, r.points[i + 1].y); if (ps.d - r.width / 2 < d) { d = ps.d - r.width / 2; wd = r.width; } } return [d, wd]; };
  for (let i = 0; i < n; i++) if (riverDist(((i % w) + 0.5) * CELL, (Math.floor(i / w) + 0.5) * CELL)[0] < 1600) riverNear[i] = 1;
  const baseAt = (px, py) => {
    const fx = clamp(px / CELL - 0.5, 0, w - 1.001), fy = clamp(py / CELL - 0.5, 0, h - 1.001), x0 = Math.floor(fx), y0 = Math.floor(fy), tx = fx - x0, ty = fy - y0;
    return (base[y0 * w + x0] * (1 - tx) + base[y0 * w + x0 + 1] * tx) * (1 - ty) + (base[(y0 + 1) * w + x0] * (1 - tx) + base[(y0 + 1) * w + x0 + 1] * tx) * ty;
  };
  // the one elevation function of the region: every settlement's terrain is a window of it
  const elevationAt = (px, py) => {
    let e = baseAt(px, py);
    const ci = clamp(Math.floor(py / CELL), 0, h - 1) * w + clamp(Math.floor(px / CELL), 0, w - 1);
    if (riverNear[ci] && e > -1) {
      const [d] = riverDist(px, py);
      if (d < 0) e = -3.5;
      else if (d < 900) e = Math.min(e, 2 + (e - 2) * smooth(0, 900, d) + 0); // a broad valley floor
    }
    return e;
  };
  const elevation = new Float32Array(n), water = new Uint8Array(n), slope = new Float32Array(n), buildability = new Float32Array(n);
  for (let i = 0; i < n; i++) { elevation[i] = elevationAt(((i % w) + 0.5) * CELL, (Math.floor(i / w) + 0.5) * CELL); water[i] = elevation[i] < 0 ? 1 : 0; }
  let waterCells = 0;
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const i = y * w + x, E = (xx, yy) => Math.max(0, elevation[clamp(yy, 0, h - 1) * w + clamp(xx, 0, w - 1)]);
    slope[i] = Math.hypot((E(x + 1, y) - E(x - 1, y)) / (2 * CELL), (E(x, y + 1) - E(x, y - 1)) / (2 * CELL));
    buildability[i] = water[i] ? 0 : 1 - smooth(0.035, 0.13, slope[i]);
    waterCells += water[i];
  }
  // open sea = water connected to the edge in a large body; rivers are narrow water
  const sea = new Uint8Array(n);
  { const comps = labelComponents(water, w, h); comps.sizes.forEach((sz, l) => { if (sz > 0.01 * n) for (let i = 0; i < n; i++) if (comps.labels[i] === l) sea[i] = 1; }); }
  region.terrain = { size, cell: CELL, w, h, n, elevation, water, sea, slope, buildability, rivers, coastal, seaAngle: coastal ? seaAngle : null, elevationAt, waterShare: waterCells / n, maxElevation: elevation.reduce((a, b) => Math.max(a, b), 0) };
  log(`region ${size / 1000} km square, ${coastal ? 'coastal' : 'inland'}, ${rivers.length} river${rivers.length > 1 ? 's' : ''}, ${Math.round((100 * waterCells) / n)}% water`);
}

// ---------------------------------------------------------------- 2. population -> settlements
const NAME_A = ['Vel', 'Kar', 'Mor', 'Tes', 'Al', 'Bren', 'Dor', 'Est', 'Fal', 'Gar', 'Hal', 'Ist', 'Lor', 'Mar', 'Nor', 'Or', 'Pel', 'Quen', 'Ros', 'Sar', 'Tor', 'Ul', 'Var', 'Wes', 'Yar', 'Zel'];
const NAME_B = ['mora', 'th', 'ia', 'den', 'holm', 'ova', 'ine', 'ara', 'wick', 'stad', 'mont', 'bury', 'esti', 'ano', 'field', 'haven', 'ford', 'grad', 'ona', 'ey'];

function planSettlementSystem(region, rng, log) {
  const P = region.regionalPopulationTarget, cfg = region.config;
  const T = region.terrain;
  let land = 0, good = 0; for (let i = 0; i < T.n; i++) if (!T.water[i]) { land++; if (T.buildability[i] > 0.6) good++; }
  const rugged = good / Math.max(1, land) < 0.72;
  // the usual region has one clearly dominant city; the other forms are possible, not the default
  const weights = { DOMINANT_CORE: 0.52, MONOCENTRIC: 0.14, POLYCENTRIC: rugged ? 0.26 : 0.12, TWIN_CORE: 0.1, LINEAR_CORRIDOR: T.coastal ? 0.16 : 0.07 };
  let profile = LEGACY_STRUCTURE[cfg.structure] || (POPULATION_PROFILES[cfg.structure] ? cfg.structure : null);
  const auto = !profile;
  if (auto) { let u = rng.next() * Object.values(weights).reduce((x, y) => x + y, 0); for (const [k, v] of Object.entries(weights)) { u -= v; if (u <= 0) { profile = k; break; } } profile = profile || 'DOMINANT_CORE'; }
  const spec = POPULATION_PROFILES[profile], cap = SIZE_PRESETS.megacity.popRange[1], alpha = spec.alpha;
  const structure = profile.toLowerCase();
  const primary = clamp(Math.round((rng.range(spec.share[0], spec.share[1]) * P) / 1000) * 1000, 120000, cap);
  // rank-size: the k-th city is primary / k^alpha. The ranked cities take most of the region;
  // what is left is spread over a tail of small cities and towns, each smaller than the last.
  const pops = [primary];
  let sum = primary, prev = primary;
  const tailStart = Math.max(70000, 0.035 * primary);
  for (let k = 2; pops.length < MAX_SETTLEMENTS - 4 && sum < P * spec.ranked; k++) {
    let p = spec.twin && k === 2 ? primary * rng.range(spec.twin[0], spec.twin[1]) : (primary / (spec.twin ? k - 0.7 : k) ** alpha) * rng.range(0.88, 1.12);
    p = Math.round(Math.min(p, prev * 0.96) / 1000) * 1000;
    if (p < tailStart) break;
    if (sum + p > P * 1.02) break;
    pops.push(p); sum += p; prev = p;
  }
  // the tail starts no larger than a town, unless that many towns could not hold what is left
  const slots = MAX_SETTLEMENTS - pops.length, left = P * 0.985 - sum;
  const tail0 = Math.min(prev * 0.9, Math.max(Math.min(prev * 0.85, 120000), slots > 0 ? (left * 0.1) / (1 - 0.9 ** slots) : 0));
  for (let t = tail0; pops.length < MAX_SETTLEMENTS && sum < P * 0.985 && t >= 20000; t *= 0.9) {
    let p = Math.round((t * rng.range(0.92, 1.08)) / 1000) * 1000;
    if (sum + p > P * 1.02) p = Math.round((P - sum) / 1000) * 1000;
    if (p < 20000) break;
    pops.push(p); sum += p;
  }
  // if the list is full and people are still unhoused (a primary city at its limit), every lower rank grows in proportion: the order is kept
  if (sum < P * 0.95 && pops.length > 1) {
    const f = (P * 0.985 - primary) / (sum - primary);
    sum = primary;
    for (let k = 1; k < pops.length; k++) { pops[k] = Math.round(Math.min(pops[k] * f, pops[k - 1] * 0.96, cap) / 1000) * 1000; sum += pops[k]; }
  }
  const names = new Set();
  const settlements = pops.map((pop, k) => {
    const scale = k === 0 ? 'PRIMARY_CITY' : pop >= 250000 ? 'MAJOR_CITY' : pop >= 100000 ? 'SECONDARY_CITY' : pop >= 40000 ? 'SMALL_CITY' : 'LOCAL_TOWN';
    let name; do { name = rng.pick(NAME_A) + rng.pick(NAME_B); } while (names.has(name)); names.add(name);
    // centres are not equal: the regional hierarchy gives each a different weight
    const centreStrength = k === 0 ? 'DOMINANT' : k === 1 && pop > 0.45 * primary ? 'STRONG' : pop >= 60000 ? 'ORDINARY' : rng.chance(0.5) ? 'ORDINARY' : 'WEAK';
    return { id: `settlement_${String(k + 1).padStart(2, '0')}`, type: 'settlement', createdByStage: 'regionalPlan', name, rank: k + 1, regionalImportance: Math.round(100 * (pop / primary) ** 0.6) / 100, scale, role: 'MIXED', populationTarget: pop, centreStrength, citySize: sizeFor(pop), radius: radiusFor(pop) };
  });
  region.populationProfile = profile;
  const axis = profile === 'LINEAR_CORRIDOR' ? (T.coastal ? T.seaAngle + Math.PI / 2 : rng.range(0, Math.PI)) : null;
  region.regionalPlan = { structure, populationProfile: profile, profileChosenBy: auto ? (rugged && profile === 'POLYCENTRIC' ? 'broken_terrain_favours_several_centres' : T.coastal && profile === 'LINEAR_CORRIDOR' ? 'coast_draws_the_settlements_into_a_line' : 'usual_form_for_a_region') : 'set_by_the_user', primaryShare: primary / P, secondShare: (pops[1] || 0) / P, rankSizeExponent: alpha, allocatedPopulation: sum, dispersedPopulation: Math.max(0, P - sum), settlementCount: settlements.length, corridorAxis: axis };
  region.settlements = settlements;
  log(`${profile} region: ${settlements.length} settlements, primary city ${(primary / 1000).toFixed(0)}k (${Math.round((100 * primary) / P)}% of ${(P / 1e6).toFixed(2)}M), ${settlements.filter((s) => s.scale === 'MAJOR_CITY').length} major, ${settlements.filter((s) => s.scale === 'SECONDARY_CITY').length} secondary, ${settlements.filter((s) => s.scale === 'SMALL_CITY').length} small, ${settlements.filter((s) => s.scale === 'LOCAL_TOWN').length} towns`);
}

// ---------------------------------------------------------------- 3. sites and relations
function planSites(region, rng, log) {
  const T = region.terrain, { w, h, size } = T, P = region.regionalPopulationTarget;
  // summed-area table of buildability, for "how much usable land is around here"
  const sat = new Float64Array((w + 1) * (h + 1));
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) sat[(y + 1) * (w + 1) + x + 1] = T.buildability[y * w + x] + sat[y * (w + 1) + x + 1] + sat[(y + 1) * (w + 1) + x] - sat[y * (w + 1) + x];
  const boxMean = (cx, cy, half) => { const x0 = clamp(Math.floor((cx - half) / CELL), 0, w), x1 = clamp(Math.ceil((cx + half) / CELL), 0, w), y0 = clamp(Math.floor((cy - half) / CELL), 0, h), y1 = clamp(Math.ceil((cy + half) / CELL), 0, h); const a = (x1 - x0) * (y1 - y0); return a ? (sat[y1 * (w + 1) + x1] - sat[y0 * (w + 1) + x1] - sat[y1 * (w + 1) + x0] + sat[y0 * (w + 1) + x0]) / a : 0; };
  const waterWithin = (cx, cy, r, seaOnly) => { const m = seaOnly ? T.sea : T.water, c = Math.ceil(r / CELL), x0 = Math.floor(cx / CELL), y0 = Math.floor(cy / CELL); let best = Infinity; for (let y = Math.max(0, y0 - c); y <= Math.min(h - 1, y0 + c); y++) for (let x = Math.max(0, x0 - c); x <= Math.min(w - 1, x0 + c); x++) if (m[y * w + x]) best = Math.min(best, Math.hypot(x - x0, y - y0) * CELL); return best; };
  const suitability = (x, y, s) => {
    const win = SIZE_PRESETS[s.citySize].mapSize / 2;
    if (x < win + 500 || y < win + 500 || x > size - win - 500 || y > size - win - 500) return -Infinity;
    const ci = Math.floor(y / CELL) * w + Math.floor(x / CELL);
    if (T.water[ci] || T.buildability[ci] < 0.6) return -Infinity;
    const land = boxMean(x, y, s.radius * 1.15);
    if (land < 0.55) return -Infinity;
    const wd = waterWithin(x, y, 6000, false);
    return 2.2 * land + (wd < 4500 ? 0.35 * (1 - Math.abs(wd - 1500) / 4500) : 0) + 0.25 * boxMean(x, y, s.radius * 2.2); // room to grow
  };
  const placed = [], relations = [];
  // in a LINEAR_CORRIDOR region the settlements keep to one line through the primary city
  const axis = region.regionalPlan.corridorAxis, offAxis = (x, y) => (axis == null || !placed.length ? 0 : (2.4 * Math.abs(-(x - placed[0].position.x) * Math.sin(axis) + (y - placed[0].position.y) * Math.cos(axis))) / (0.25 * size));
  const clearOf = (x, y, s, host, factor) => placed.every((o) => { const need = (s.radius + o.radius) * (o === host ? factor : 1) + (o === host ? 0 : 1200); return Math.hypot(x - o.position.x, y - o.position.y) >= need; });
  // how tightly the region is knit: large regions are metropolitan, small ones a scatter of towns
  const pGlue = P >= 4e6 ? 0.42 : P >= 1.8e6 ? 0.3 : P >= 9e5 ? 0.18 : 0.08, pNear = P >= 1.8e6 ? 0.25 : 0.18;
  for (const s of region.settlements) {
    let best = null, intended = 'SEPARATE', host = null, why;
    if (!placed.length) {
      for (let y = CELL; y < size; y += 3 * CELL) for (let x = CELL; x < size; x += 3 * CELL) {
        const sc = suitability(x, y, s) - 1.4 * Math.hypot(x - size / 2, y - size / 2) / size + rng.range(0, 0.05);
        if (!best || sc > best.sc) best = { x, y, sc };
      }
      why = 'largest_area_of_good_building_land_near_the_middle_of_the_region';
    } else {
      const u = rng.next(), big = s.populationTarget >= 60000;
      intended = big && u < pGlue ? 'GLUED' : u < pGlue + pNear ? 'NEAR_TOUCHING' : 'SEPARATE';
      // a host to settle beside: bigger places attract more, the primary most of all
      let tw = 0; const weights = placed.map((o) => { const v = o.populationTarget ** 0.7 / (1 + 0.6 * o.attached); tw += v; return v; });
      let pickU = rng.next() * tw; host = placed[0];
      for (let k = 0; k < placed.length; k++) { pickU -= weights[k]; if (pickU <= 0) { host = placed[k]; break; } }
      const tryRing = (kind) => {
        const gap = kind === 'GLUED' ? -0.18 * (s.radius + host.radius) : kind === 'NEAR_TOUCHING' ? rng.range(300, 1300) : rng.range(3500, 9000) + 2000 * rng.next();
        const D = s.radius + host.radius + gap, factor = kind === 'GLUED' ? 0.8 : 1;
        let b = null;
        for (let k = 0; k < 40; k++) for (const f of [1, 0.94, 1.07]) {
          const a = (k / 40) * Math.PI * 2, x = Math.round((host.position.x + Math.cos(a) * D * f) / CELL) * CELL, y = Math.round((host.position.y + Math.sin(a) * D * f) / CELL) * CELL;
          if (!clearOf(x, y, s, host, factor)) continue;
          const sc = suitability(x, y, s) + rng.range(0, 0.12) - offAxis(x, y);
          if (sc > -Infinity && (!b || sc > b.sc)) b = { x, y, sc };
        }
        return b;
      };
      for (const kind of intended === 'GLUED' ? ['GLUED', 'NEAR_TOUCHING', 'SEPARATE'] : intended === 'NEAR_TOUCHING' ? ['NEAR_TOUCHING', 'SEPARATE'] : ['SEPARATE']) { best = tryRing(kind); if (best) { intended = kind; break; } }
      why = best ? { GLUED: `grown_together_with_${host.name}`, NEAR_TOUCHING: `founded_beside_${host.name}_with_open_land_between`, SEPARATE: `separate_town_in_the_orbit_of_${host.name}` }[intended] : null;
      if (!best) { // anywhere there is room
        host = null; intended = 'SEPARATE';
        for (let y = CELL; y < size; y += 3 * CELL) for (let x = CELL; x < size; x += 3 * CELL) { if (!clearOf(x, y, s, null, 1)) continue; const sc = suitability(x, y, s) + rng.range(0, 0.05); if (sc > -Infinity && (!best || sc > best.sc)) best = { x, y, sc }; }
        why = 'free_standing_site_on_good_land';
      }
    }
    if (!best) { s.unplaced = true; continue; }
    if (host) host.attached++;
    const mapSize = SIZE_PRESETS[s.citySize].mapSize;
    Object.assign(s, {
      position: { x: best.x, y: best.y }, attached: 0, hostId: host ? host.id : null, intendedRelation: intended,
      origin: { x: Math.round((best.x - mapSize / 2) / 50) * 50, y: Math.round((best.y - mapSize / 2) / 50) * 50 }, mapSize,
      foundingBoundary: circlePolygon(best.x, best.y, s.radius, 36), growthBoundary: circlePolygon(best.x, best.y, s.radius * 1.5, 36),
      influenceRadius: Math.round(s.radius * (2.2 + 3 * (s.populationTarget / P))), orientation: rng.range(0, Math.PI),
      reason: why,
    });
    placed.push(s);
  }
  region.settlements = region.settlements.filter((s) => !s.unplaced);
  // roles follow the site
  const used = new Set();
  for (const s of region.settlements) {
    const seaD = waterWithin(s.position.x, s.position.y, s.radius + 2500, true);
    let role = 'MIXED';
    if (s.rank === 1) role = rng.chance(0.3) ? 'ADMINISTRATIVE' : 'MIXED';
    else if (seaD < s.radius + 1500 && !used.has('PORT') && s.populationTarget >= 50000) role = 'PORT';
    else if (seaD < s.radius + 1500 && s.populationTarget < 60000 && rng.chance(0.5)) role = 'RESORT';
    else { const u = rng.next(); role = u < 0.22 ? 'INDUSTRIAL' : u < 0.32 && !used.has('UNIVERSITY') ? 'UNIVERSITY' : u < 0.42 && !used.has('LOGISTICS') ? 'LOGISTICS' : u < 0.45 && !used.has('MILITARY') ? 'MILITARY' : 'MIXED'; }
    used.add(role); s.role = role;
    if (role === 'ADMINISTRATIVE' || role === 'PORT' || role === 'UNIVERSITY' || role === 'LOGISTICS') s.regionalImportance = Math.min(1, Math.round(100 * (s.regionalImportance + 0.08)) / 100);
    if (s.scale === 'LOCAL_TOWN' && role !== 'MIXED') s.scale = 'SPECIALIZED_TOWN';
    // each settlement is planned in its own way
    const pool = s.rank === 1 ? ['default', 'radial_formal', 'polycentric', 'centralised'] : role === 'INDUSTRIAL' || role === 'LOGISTICS' ? ['strong_grid', 'default', 'flat_loose'] : role === 'RESORT' ? ['organic', 'flat_loose'] : ['default', 'strong_grid', 'organic', 'radial_formal', 'centralised', 'flat_loose', 'rugged'];
    s.planningProfile = rng.pick(pool);
    s.administrativeId = `adm_${s.id.slice(-2)}`;
    s.reason = `${s.scale.toLowerCase()}_with_${role.toLowerCase()}_role_${s.reason}`;
  }
  // relations between neighbours, and the boundary each pair shares
  const S = region.settlements, parent = S.map((_, i) => i), find = (i) => (parent[i] === i ? i : (parent[i] = find(parent[i])));
  for (let i = 0; i < S.length; i++) for (let j = i + 1; j < S.length; j++) {
    const a = S[i], b = S[j], D = Math.hypot(b.position.x - a.position.x, b.position.y - a.position.y), gap = D - a.radius - b.radius;
    const overlap = Math.abs(a.position.x - b.position.x) < (a.mapSize + b.mapSize) / 2 && Math.abs(a.position.y - b.position.y) < (a.mapSize + b.mapSize) / 2;
    if (gap > 5000 && !overlap) continue;
    const relation = gap < 0 ? 'GLUED' : gap < 1500 ? 'NEAR_TOUCHING' : 'SEPARATE';
    const ux = (b.position.x - a.position.x) / D, uy = (b.position.y - a.position.y) / D, t = a.radius + gap / 2; // boundary: midway across the gap (or the overlap)
    const seam = { x: a.position.x + ux * t, y: a.position.y + uy * t, nx: ux, ny: uy };
    relations.push({ id: `relation_${a.id.slice(-2)}_${b.id.slice(-2)}`, type: 'settlement_relation', createdByStage: 'sites', a: a.id, b: b.id, relation, gap: Math.round(gap), distance: Math.round(D), seam, windowsOverlap: overlap, reason: relation === 'GLUED' ? 'the_two_founding_areas_overlap_so_their_fabrics_meet_at_a_shared_boundary' : relation === 'NEAR_TOUCHING' ? 'founding_areas_come_within_1500_m_of_each_other' : 'clearly_separate_settlements' });
    if (relation === 'GLUED') parent[find(i)] = find(j);
  }
  const groups = new Map();
  S.forEach((s, i) => { const g = find(i); (groups.get(g) || groups.set(g, []).get(g)).push(s); });
  let gi = 0;
  for (const members of groups.values()) {
    const id = `continuity_${String(++gi).padStart(2, '0')}`, kind = members.length >= 3 ? 'CONTINUOUS_METROPOLITAN' : members.length === 2 ? 'GLUED' : 'FREE_STANDING';
    for (const s of members) { s.urbanContinuityGroup = id; s.continuity = kind; s.metroRegionId = Math.hypot(s.position.x - S[0].position.x, s.position.y - S[0].position.y) <= S[0].influenceRadius + s.radius ? 'metro_01' : null; }
  }
  for (const r of relations) if (r.relation === 'GLUED' && S.find((s) => s.id === r.a).continuity === 'CONTINUOUS_METROPOLITAN') r.partOf = 'CONTINUOUS_METROPOLITAN';
  region.relations = relations;
  log(`${S.length} sites; relations: ${['GLUED', 'NEAR_TOUCHING', 'SEPARATE'].map((k) => `${relations.filter((r) => r.relation === k).length} ${k.toLowerCase()}`).join(', ')}; ${[...groups.values()].filter((m) => m.length > 1).length} continuous urban group(s), largest ${Math.max(...[...groups.values()].map((m) => m.length))} settlements; roles: ${S.map((s) => s.role).filter((r) => r !== 'MIXED').join(', ').toLowerCase() || 'all mixed'}`);
}

// ---------------------------------------------------------------- 4. regional infrastructure
function planInfrastructure(region, rng, log) {
  const T = region.terrain, { w, h, n, size } = T, S = region.settlements;
  const cellOf = (p) => clamp(Math.floor(p.y / CELL), 0, h - 1) * w + clamp(Math.floor(p.x / CELL), 0, w - 1);
  const centre = (c) => ({ x: ((c % w) + 0.5) * CELL, y: (Math.floor(c / w) + 0.5) * CELL });
  const owner = new Int16Array(n).fill(-1); // which settlement's founding area a cell lies in
  S.forEach((s, k) => { const c = Math.ceil(s.radius / CELL), x0 = Math.floor(s.position.x / CELL), y0 = Math.floor(s.position.y / CELL); for (let y = Math.max(0, y0 - c); y <= Math.min(h - 1, y0 + c); y++) for (let x = Math.max(0, x0 - c); x <= Math.min(w - 1, x0 + c); x++) if (Math.hypot(x - x0, y - y0) * CELL <= s.radius) owner[y * w + x] = k; });
  const dl = NEIGH16.map(([dx, dy]) => Math.hypot(dx, dy)), dx_ = NEIGH16.map(([dx], k) => dx / dl[k]), dy_ = NEIGH16.map(([, dy], k) => dy / dl[k]);
  const used = { road: new Uint8Array(n), rail: new Uint8Array(n) };
  const route = (from, to, kind, skip) => {
    const gx = to % w, gy = Math.floor(to / w), rail = kind === 'rail';
    const path = leastCostPath({
      w, h, start: from, goal: to, neighbours: NEIGH16,
      stepCost: (a, b, k, arrival) => {
        if (T.sea[b]) return Infinity;
        let c = dl[k] * CELL * (1 + (rail ? 60 : 22) * T.slope[b]);
        if (T.water[b]) c *= 6; // a river crossing
        if (owner[b] >= 0 && !skip.includes(owner[b])) c *= 3.2; // keep out of a third settlement: pass it by
        if (used[kind][b]) c *= 0.5;
        if (arrival >= 0) { const dot = dx_[k] * dx_[arrival] + dy_[k] * dy_[arrival]; c += (1 - dot) * (rail ? 9 : 2) * CELL + (rail && dot < 0.7 ? 6000 : 0); }
        return c;
      },
      heuristic: (i) => 0.6 * CELL * Math.hypot((i % w) - gx, Math.floor(i / w) - gy),
    });
    if (!path) return null;
    for (const c of path.cells) used[kind][c] = 1;
    const pts = simplifyDP(path.cells.map(centre), CELL * 0.9);
    const fit = pts.length > 2 ? fitAlignment(pts, { minRadius: rail ? 1500 : 500, step: 200, maxShift: rail ? 900 : 450 }) : { points: pts };
    return fit.points;
  };
  // exits from the region: where the inland edges are open land
  const exits = [];
  for (const [ex, ey, name] of [[0.5, 0.02, 'north'], [0.98, 0.5, 'east'], [0.5, 0.98, 'south'], [0.02, 0.5, 'west']]) {
    let best = null;
    for (let t = -0.3; t <= 0.3; t += 0.05) { const p = { x: (ex + (ex === 0.5 ? t : 0)) * size, y: (ey + (ey === 0.5 ? t : 0)) * size }, c = cellOf(p); if (!T.water[c] && T.buildability[c] > 0.5 && (!best || Math.abs(t) < Math.abs(best.t))) best = { ...p, t, name }; }
    if (best) exits.push(best);
  }
  const prim = S[0];
  exits.sort((a, b) => Math.hypot(a.x - prim.position.x, a.y - prim.position.y) - Math.hypot(b.x - prim.position.x, b.y - prim.position.y));
  const dist2 = (a, b) => Math.hypot(a.position.x - b.position.x, a.position.y - b.position.y);

  // --- roads: a tree that reaches every settlement, plus direct links between the big ones
  const links = [], inTree = [0];
  while (inTree.length < S.length) {
    let best = null;
    for (const i of inTree) for (let j = 0; j < S.length; j++) { if (inTree.includes(j)) continue; const d = dist2(S[i], S[j]) / (S[i].populationTarget ** 0.15); if (!best || d < best.d) best = { d, i, j }; }
    links.push([best.i, best.j, 'network_tree']); inTree.push(best.j);
  }
  // A direct road between two large cities is redundancy, and redundancy alone is not a reason:
  // it is built only where it saves a real detour for a real flow of traffic.
  const rejected = [], utilityOf = new Map();
  {
    const treeDist = (from) => { const d = new Array(S.length).fill(Infinity); d[from] = 0; const q = [from]; while (q.length) { const u = q.shift(); for (const [a, b] of links) { const v = a === u ? b : b === u ? a : -1; if (v >= 0 && d[v] === Infinity) { d[v] = d[u] + dist2(S[u], S[v]); q.push(v); } } } return d; };
    const cands = [];
    for (let i = 0; i < S.length; i++) for (let j = i + 1; j < S.length; j++) {
      if (Math.min(S[i].populationTarget, S[j].populationTarget) < 150000 || links.some((l) => (l[0] === i && l[1] === j) || (l[1] === i && l[0] === j))) continue;
      if (i > 0 && Math.min(S[i].populationTarget, S[j].populationTarget) < 300000) continue; // between secondary cities only when both are large
      cands.push([i, j]);
    }
    const scored = [];
    for (const [i, j] of cands) {
      const direct = dist2(S[i], S[j]), viaTree = treeDist(i)[j], detour = viaTree / direct;
      const flow = (S[i].populationTarget * S[j].populationTarget) / (direct * direct), flow0 = (S[0].populationTarget * (S[1] ? S[1].populationTarget : S[0].populationTarget)) / (20000 * 20000);
      const c = { detourReduction: clamp((detour - 1) / 0.8, 0, 1), settlementDemand: clamp(Math.sqrt(flow / flow0), 0, 1), regionalConnectivity: i === 0 ? 0.6 : 0.3, parallelsExistingRoute: detour < 1.2 ? 1 : 0, longEmptyRun: clamp((direct - 30000) / 40000, 0, 1) };
      const utility = 0.45 * c.detourReduction + 0.35 * c.settlementDemand + 0.2 * c.regionalConnectivity - 0.4 * c.parallelsExistingRoute - 0.25 * c.longEmptyRun;
      scored.push({ i, j, utility, c, detour });
    }
    scored.sort((a, b) => b.utility - a.utility || a.i - b.i || a.j - b.j);
    for (const o of scored) {
      const direct = dist2(S[o.i], S[o.j]), detour = treeDist(o.i)[o.j] / direct; // earlier links may already have shortened the way
      if (o.utility >= ({ sparse: 0.58, dense: 0.28 }[region.config.roadIntensity] ?? 0.42) && detour >= 1.25) { links.push([o.i, o.j, 'direct_link_saving_a_' + Math.round((detour - 1) * 100) + '_percent_detour_between']); utilityOf.set(`${o.i}:${o.j}`, { utility: Math.round(o.utility * 100) / 100, utilityComponents: o.c }); }
      else rejected.push({ type: 'regional_link', createdByStage: 'infrastructure', from: S[o.i].id, to: S[o.j].id, utility: Math.round(o.utility * 100) / 100, utilityComponents: o.c, rejectedReason: detour < 1.25 ? 'an_existing_road_already_makes_this_journey_almost_directly' : o.c.longEmptyRun > 0.5 ? 'a_long_road_across_empty_country_for_too_little_traffic' : 'would_only_close_a_loop_in_the_network_without_carrying_enough_traffic' });
    }
  }
  region.rejectedLinks = rejected;
  const roads = [];
  const settleById = new Map(S.map((s) => [s.id, s]));
  for (const s of S) { s.gateways = []; s.railEntries = []; s.throughPairs = []; }
  const relationOf = (a, b) => region.relations.find((r) => (r.a === a.id && r.b === b.id) || (r.a === b.id && r.b === a.id));
  // where a line leaves a settlement's window (walking away from its centre)
  const exitPoint = (pts, s, fromStart) => {
    const seq = fromStart ? pts : [...pts].reverse(), half = s.mapSize / 2 - 200, inside = (p) => Math.abs(p.x - s.position.x) < half && Math.abs(p.y - s.position.y) < half;
    for (let i = 1; i < seq.length; i++) if (inside(seq[i - 1]) && !inside(seq[i])) {
      let a = seq[i - 1], b = seq[i];
      for (let k = 0; k < 12; k++) { const m = { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }; if (inside(m)) a = m; else b = m; }
      return { point: a, index: fromStart ? i : seq.length - 1 - i };
    }
    return null;
  };
  const seamPoint = (pts, rel) => { // where a line crosses the boundary between two neighbours
    for (let i = 1; i < pts.length; i++) { const d0 = (pts[i - 1].x - rel.seam.x) * rel.seam.nx + (pts[i - 1].y - rel.seam.y) * rel.seam.ny, d1 = (pts[i].x - rel.seam.x) * rel.seam.nx + (pts[i].y - rel.seam.y) * rel.seam.ny; if (d0 * d1 <= 0 && d0 !== d1) { const t = d0 / (d0 - d1); return { x: pts[i - 1].x + (pts[i].x - pts[i - 1].x) * t, y: pts[i - 1].y + (pts[i].y - pts[i - 1].y) * t }; } }
    return { x: rel.seam.x, y: rel.seam.y };
  };
  const local = (s, p) => ({ x: p.x - s.origin.x, y: p.y - s.origin.y });
  let rid = 0;
  const addRoad = (a, b, exit, why) => {
    const pts = route(cellOf(a.position), b ? cellOf(b.position) : cellOf(exit), 'road', b ? [S.indexOf(a), S.indexOf(b)] : [S.indexOf(a)]);
    if (!pts || pts.length < 2) return;
    const id = `regroad_${String(++rid).padStart(2, '0')}`, rel = b ? relationOf(a, b) : null;
    const cls = !b || Math.min(a.populationTarget, b.populationTarget) >= 120000 ? 'REGIONAL_HIGHWAY' : 'INTERCITY_ROAD';
    let geometry = pts, seam = null;
    if (rel && rel.windowsOverlap && rel.relation !== 'SEPARATE') { // neighbours: the road is handed over at their shared boundary
      seam = seamPoint(pts, rel);
      a.gateways.push({ ...local(a, seam), regionalRoadId: id, towards: b.name, seam: true });
      b.gateways.push({ ...local(b, seam), regionalRoadId: id, towards: a.name, seam: true });
      geometry = [seam];
    } else {
      const ea = exitPoint(pts, a, true), eb = b ? exitPoint(pts, b, false) : null;
      if (ea) a.gateways.push({ ...local(a, ea.point), regionalRoadId: id, towards: b ? b.name : `the ${exit.name}` });
      if (eb) b.gateways.push({ ...local(b, eb.point), regionalRoadId: id, towards: a.name });
      geometry = pts.slice(ea ? ea.index : 0, eb ? eb.index + 1 : pts.length);
      if (ea) geometry.unshift(ea.point);
      if (eb) geometry.push(eb.point);
    }
    // a settlement the road runs through on its way: an explicit decision, taken later by that settlement's own plan
    const through = [];
    for (const c of S) {
      if (c === a || c === b) continue;
      let nearest = Infinity; for (const p of pts) nearest = Math.min(nearest, Math.hypot(p.x - c.position.x, p.y - c.position.y));
      if (nearest > c.radius * 1.15) continue;
      const half = c.mapSize / 2 - 200, inside = (p) => Math.abs(p.x - c.position.x) < half && Math.abs(p.y - c.position.y) < half;
      let first = null, last = null;
      for (let i = 1; i < pts.length; i++) { if (!inside(pts[i - 1]) && inside(pts[i]) && !first) first = pts[i]; if (inside(pts[i - 1]) && !inside(pts[i])) last = pts[i - 1]; }
      if (first && last) { c.gateways.push({ ...local(c, first), regionalRoadId: id, towards: a.name }, { ...local(c, last), regionalRoadId: id, towards: b ? b.name : `the ${exit.name}` }); c.throughPairs.push([id, id]); through.push(c.id); }
    }
    roads.push({ id, type: cls, createdByStage: 'infrastructure', reason: `${why}_${a.name.toLowerCase()}_to_${b ? b.name.toLowerCase() : 'beyond_the_region_' + exit.name}`, system: cls === 'REGIONAL_HIGHWAY' ? 'LIMITED_ACCESS' : 'STREET', from: a.id, to: b ? b.id : null, exit: b ? null : exit.name, points: geometry, routed: pts, length: polylineLength(geometry), handedOverAtSeam: !!seam, passesThrough: through });
  };
  for (const [i, j, why] of links) { addRoad(S[i], S[j], null, why); const u = utilityOf.get(`${i}:${j}`); if (u && roads.length) Object.assign(roads[roads.length - 1], u); }
  for (const ex of exits.slice(0, S.length > 4 ? 3 : 2)) addRoad(prim, null, ex, 'road_out_of_the_region_from');
  region.regionalRoads = roads;

  // --- rail: one main line through the largest cities, branches to the others that warrant it
  const railS = S.filter((s) => s.populationTarget >= ({ sparse: 130000, dense: 30000 }[region.config.railIntensity] ?? 60000) || ['PORT', 'INDUSTRIAL', 'LOGISTICS'].includes(s.role));
  for (const s of S) s.rail = railS.includes(s);
  const lines = [];
  let lid = 0;
  const addRail = (a, b, exit, cls, why) => {
    const pts = route(cellOf(a.position), b ? cellOf(b.position) : cellOf(exit), 'rail', b ? [S.indexOf(a), S.indexOf(b)] : [S.indexOf(a)]);
    if (!pts || pts.length < 2) return;
    const id = `regrail_${String(++lid).padStart(2, '0')}`, rel = b ? relationOf(a, b) : null;
    let geometry, seam = null;
    if (rel && rel.windowsOverlap && rel.relation !== 'SEPARATE') { // neighbours: the line passes from one to the other at their boundary
      seam = seamPoint(pts, rel);
      a.railEntries.push({ ...local(a, seam), regionalRailId: id, seam: true });
      b.railEntries.push({ ...local(b, seam), regionalRailId: id, seam: true });
      geometry = [seam, seam];
    } else {
      const ea = exitPoint(pts, a, true), eb = b ? exitPoint(pts, b, false) : null;
      if (ea) a.railEntries.push({ ...local(a, ea.point), regionalRailId: id });
      if (eb) b.railEntries.push({ ...local(b, eb.point), regionalRailId: id });
      geometry = pts.slice(ea ? ea.index : 0, eb ? eb.index + 1 : pts.length);
      if (ea) geometry.unshift(ea.point);
      if (eb) geometry.push(eb.point);
      if (geometry.length < 2) geometry = [ea ? ea.point : pts[0], eb ? eb.point : pts[pts.length - 1]];
    }
    lines.push({ id, type: cls, createdByStage: 'infrastructure', reason: `${why}_${a.name.toLowerCase()}_${b ? b.name.toLowerCase() : 'beyond_the_region_' + exit.name}`, system: 'RAIL', profile: cls, from: a.id, to: b ? b.id : null, exit: b ? null : exit.name, points: geometry, length: polylineLength(geometry), handedOverAtSeam: !!seam });
  };
  if (railS.length) {
    const main = railS.filter((s) => s.populationTarget >= 150000 || s === prim);
    // order the main-line cities along the region's long axis through the primary city
    const ax = exits.length ? Math.atan2(exits[0].y - prim.position.y, exits[0].x - prim.position.x) : 0, proj = (s) => (s.position.x - prim.position.x) * Math.cos(ax) + (s.position.y - prim.position.y) * Math.sin(ax);
    main.sort((p, q) => proj(p) - proj(q));
    for (let i = 0; i + 1 < main.length; i++) addRail(main[i], main[i + 1], null, 'INTERCITY_RAIL', 'main_line_between');
    const far = exits.slice().sort((a, b) => ((b.x - prim.position.x) * Math.cos(ax) + (b.y - prim.position.y) * Math.sin(ax)) - ((a.x - prim.position.x) * Math.cos(ax) + (a.y - prim.position.y) * Math.sin(ax)));
    if (far.length) addRail(main[main.length - 1], null, far[0], 'INTERCITY_RAIL', 'main_line_out_of_the_region_from');
    if (far.length > 1) addRail(main[0], null, far[far.length - 1], 'INTERCITY_RAIL', 'main_line_out_of_the_region_from');
    for (const s of railS) {
      if (main.includes(s)) continue;
      const hub = main.slice().sort((p, q) => dist2(p, s) - dist2(q, s))[0];
      const freight = ['PORT', 'INDUSTRIAL', 'LOGISTICS'].includes(s.role) && s.populationTarget < 60000;
      addRail(s, hub, null, freight ? 'FREIGHT_RAIL' : 'REGIONAL_RAIL', freight ? 'freight_corridor_between' : 'regional_branch_between');
    }
  }
  region.regionalRail = lines;
  allocateInstitutions(region, log);
  assignMacroGrowth(region, log);

  // --- regional anchors and protected land
  const anchors = [];
  for (const s of S) if (s.role === 'PORT') anchors.push({ id: `reganchor_port_${s.id.slice(-2)}`, type: 'PORT', createdByStage: 'infrastructure', reason: `sea_port_of_${s.name.toLowerCase()}`, settlementId: s.id, position: s.position });
  if (region.regionalPopulationTarget >= 1500000) {
    let best = null;
    for (let y = 10; y < h - 10; y += 3) for (let x = 10; x < w - 10; x += 3) {
      const p = { x: (x + 0.5) * CELL, y: (y + 0.5) * CELL }, d = Math.hypot(p.x - prim.position.x, p.y - prim.position.y), i = y * w + x;
      if (d < prim.radius + 4000 || d > prim.radius + 16000 || T.buildability[i] < 0.9 || T.water[i] || S.some((s) => Math.hypot(p.x - s.position.x, p.y - s.position.y) < s.radius + 2000)) continue;
      let flat = 0; for (let yy = y - 6; yy <= y + 6; yy++) for (let xx = x - 6; xx <= x + 6; xx++) flat += T.buildability[yy * w + xx] > 0.85 && !T.water[yy * w + xx] ? 1 : 0;
      const sc = flat / 169 - d / 60000 + (used.road[i] ? 0.2 : 0);
      if (!best || sc > best.sc) best = { sc, p };
    }
    if (best) anchors.push({ id: 'reganchor_airport', type: 'AIRPORT', createdByStage: 'infrastructure', reason: `flat_open_site_${Math.round(Math.hypot(best.p.x - prim.position.x, best.p.y - prim.position.y) / 1000)}_km_from_${prim.name.toLowerCase()}_clear_of_every_settlement`, position: best.p });
  }
  region.regionalAnchors = anchors;
  const prot = [];
  { const mask = new Uint8Array(n); for (let i = 0; i < n; i++) mask[i] = !T.water[i] && T.slope[i] > 0.085 ? 1 : 0;
    const comps = labelComponents(mask, w, h);
    comps.sizes.forEach((sz, l) => { if (sz * CELL * CELL < 6e6) return; const rings = traceRegionRings(comps.labels, w, h, CELL, l); if (rings.length) prot.push({ id: `protected_${String(prot.length + 1).padStart(2, '0')}`, type: 'UPLAND_RESERVE', createdByStage: 'infrastructure', reason: 'steep_upland_kept_as_open_landscape', polygon: rings[0], areaKm2: (sz * CELL * CELL) / 1e6 }); }); }
  T.rivers.forEach((r, k) => prot.push({ id: `protected_river_${k + 1}`, type: 'RIVER_CORRIDOR', createdByStage: 'infrastructure', reason: 'river_and_its_floodplain_kept_as_a_green_corridor', points: r.points, width: r.width + 900 }));
  region.protectedAreas = prot;
  log(`${roads.length} regional roads (${roads.filter((r) => r.type === 'REGIONAL_HIGHWAY').length} highways, ${roads.filter((r) => r.handedOverAtSeam).length} handed over at a shared boundary, ${roads.filter((r) => r.passesThrough.length).length} passing through a settlement), ${lines.length} rail lines (${lines.filter((l) => l.type === 'INTERCITY_RAIL').length} main line sections), ${S.filter((s) => !s.rail).length} settlements without rail, ${anchors.length} regional anchors, ${prot.length} protected areas`);
}

// Institutions belong to the region, not to every town. The region's demand for each kind is
// worked out from its population and then handed down the hierarchy: the largest and most
// important settlements are served first, and a place too small to support one gets none.
const INSTITUTION_DEMAND = {
  universities: { per: 600000, minPop: 180000, cap: { megacity: 4, metropolis: 3, major: 2, medium: 1, small: 1 }, role: 'UNIVERSITY' },
  hospitals: { per: 280000, minPop: 90000, cap: { megacity: 6, metropolis: 4, major: 2, medium: 1, small: 1 } },
  stadiums: { per: 1100000, minPop: 200000, cap: { megacity: 3, metropolis: 2, major: 1, medium: 1, small: 0 } },
  culturalComplexes: { per: 800000, minPop: 250000, cap: { megacity: 3, metropolis: 2, major: 1, medium: 1, small: 0 }, role: 'ADMINISTRATIVE' },
};
function allocateInstitutions(region, log) {
  const S = region.settlements, P = region.regionalPopulationTarget, demand = {};
  for (const s of S) s.institutions = { universities: 0, colleges: 0, hospitals: 0, stadiums: 0, culturalComplexes: 0, subCentres: 0, stationClass: 'NONE', reasons: [] };
  for (const [kind, d] of Object.entries(INSTITUTION_DEMAND)) {
    demand[kind] = Math.max(1, Math.round(P / d.per));
    const weight = (s) => s.populationTarget ** 1.1 * (0.6 + 0.4 * s.regionalImportance) * (d.role && s.role === d.role ? 2.5 : 1);
    const eligible = (s) => s.populationTarget >= d.minPop || (d.role && s.role === d.role && s.populationTarget >= d.minPop / 3);
    for (let k = 0; k < demand[kind]; k++) {
      let best = null, bv = 0;
      for (const s of S) { if (!eligible(s) || s.institutions[kind] >= d.cap[s.citySize]) continue; const v = weight(s) / (s.institutions[kind] + 1); if (v > bv) { bv = v; best = s; } }
      if (!best) break;
      best.institutions[kind]++;
    }
  }
  const main = new Set(region.regionalRail.filter((l) => l.type === 'INTERCITY_RAIL').flatMap((l) => [l.from, l.to]));
  for (const s of S) {
    const I = s.institutions, pop = s.populationTarget;
    // a town without a university may still have a college
    if (!I.universities && pop >= 60000) I.colleges = 1;
    // the station is as large as the place it serves
    I.stationClass = !s.rail ? 'NONE' : s.rank === 1 ? 'HUB' : pop >= 250000 ? 'MAIN' : pop >= 100000 ? 'SIMPLE' : 'STOP';
    // sub-centres: one for every catchment the main centre cannot reach, more where a main station or a university cluster gives a second focus
    const catchment = Math.max(0, 3.6 * (pop / 1e6) ** 0.62 - 0.75), causes = [];
    let n = Math.floor(catchment);
    if (n) causes.push(`${n}_population_catchment${n > 1 ? 's' : ''}_beyond_reach_of_the_main_centre`);
    const frac = catchment - Math.floor(catchment);
    if (pop >= 90000 && frac >= 0.2 && (I.stationClass === 'HUB' || I.stationClass === 'MAIN' || (main.has(s.id) && frac >= 0.45))) { n++; causes.push('main_line_station_gives_a_second_focus'); }
    else if (pop >= 90000 && frac >= 0.35 && (I.universities >= 1 || ['INDUSTRIAL', 'PORT', 'LOGISTICS'].includes(s.role))) { n++; causes.push(I.universities ? 'university_cluster_gives_a_second_focus' : 'employment_cluster_gives_a_second_focus'); }
    I.subCentres = Math.min(n, SIZE_PRESETS[s.citySize].maxSecondary); I.subCentreCauses = causes;
    I.reasons.push(`rank_${s.rank}_of_${S.length}_importance_${s.regionalImportance}`);
  }
  region.institutionDemand = { ...demand, allocated: Object.fromEntries(Object.keys(INSTITUTION_DEMAND).map((k) => [k, S.reduce((a, s) => a + s.institutions[k], 0)])), railHubs: S.filter((s) => s.institutions.stationClass === 'HUB' || s.institutions.stationClass === 'MAIN').length };
  log(`regional demand: ${Object.entries(demand).map(([k, v]) => `${v} ${k}`).join(', ')}; ${S.filter((s) => s.institutions.universities).length} of ${S.length} settlements have a university, ${S.filter((s) => s.institutions.stationClass === 'NONE').length} have no station, ${S.filter((s) => !s.institutions.subCentres).length} have no sub-centre`);
}

// MACRO GROWTH. How a settlement spreads over its site is decided from the site: coast, river,
// broken ground, the roads that reach it, its neighbours, its size and how it is planned. Each
// pattern has its own idea of compactness, and each choice carries its reason.
export const MACRO_GROWTH = { CONCENTRIC: 1.35, GRID_EXPANSION: 1.7, RADIAL_CORRIDOR: 1.9, MULTINODAL: 1.9, ASYMMETRIC: 1.9, BIDIRECTIONAL: 2.3, LINEAR: 2.6 }; // how far, in radii, growth may reach
function assignMacroGrowth(region, log) {
  const T = region.terrain, { w, h } = T, S = region.settlements, byId = new Map(S.map((s) => [s.id, s]));
  const scan = (s, mask, r) => { let n = 0, tot = 0, sx = 0, sy = 0; const c = Math.ceil(r / CELL), x0 = Math.floor(s.position.x / CELL), y0 = Math.floor(s.position.y / CELL); for (let y = y0 - c; y <= y0 + c; y++) for (let x = x0 - c; x <= x0 + c; x++) { if ((x - x0) ** 2 + (y - y0) ** 2 > c * c) continue; tot++; if (x < 0 || y < 0 || x >= w || y >= h) continue; if (mask(y * w + x)) { n++; sx += x - x0; sy += y - y0; } } return { share: n / Math.max(1, tot), angle: Math.atan2(sy, sx) }; };
  for (const s of S) {
    const sea = scan(s, (i) => T.sea[i], s.radius * 1.3), river = scan(s, (i) => T.water[i] && !T.sea[i], s.radius * 0.9), steep = scan(s, (i) => !T.water[i] && T.buildability[i] < 0.4, s.radius * 1.4);
    const glued = region.relations.filter((r) => r.relation !== 'SEPARATE' && (r.a === s.id || r.b === s.id) && r.relation === 'GLUED').map((r) => byId.get(r.a === s.id ? r.b : r.a)).filter((o) => o.populationTarget >= 0.5 * s.populationTarget);
    const roads = s.gateways.length, big = s.citySize === 'megacity' || s.citySize === 'metropolis';
    let pattern, why, axis = null, bias = null;
    if (region.populationProfile === 'LINEAR_CORRIDOR' && s.rank > 1) { pattern = 'LINEAR'; axis = region.regionalPlan.corridorAxis; why = 'the_region_is_a_corridor_and_its_settlements_stretch_along_it'; }
    else if (sea.share > 0.12 && !big) { pattern = sea.share > 0.28 || s.role === 'RESORT' ? 'LINEAR' : 'BIDIRECTIONAL'; axis = sea.angle + Math.PI / 2; why = pattern === 'LINEAR' ? 'the_sea_takes_one_side_so_the_town_runs_along_the_shore' : 'grows_both_ways_along_the_coast'; }
    else if (steep.share > 0.3) { pattern = river.share > 0.02 ? 'LINEAR' : 'ASYMMETRIC'; axis = steep.angle + Math.PI / 2; bias = steep.angle + Math.PI; why = pattern === 'LINEAR' ? 'a_valley_between_steep_ground_leaves_one_direction_to_grow' : 'steep_ground_on_one_side_pushes_growth_to_the_other'; }
    else if (glued.length) { const g = glued[0]; pattern = 'ASYMMETRIC'; why = // no bias needed: the shared boundary itself closes that side, and the fabric still grows right up to it
      `${g.name.toLowerCase()}_closes_one_side_so_growth_goes_the_other_way`; }
    else if (sea.share > 0.12) { pattern = 'ASYMMETRIC'; bias = sea.angle + Math.PI; why = 'a_large_city_on_the_coast_can_only_grow_inland'; }
    else if (s.citySize === 'megacity' || s.planningProfile === 'polycentric') { pattern = 'MULTINODAL'; axis = s.orientation; why = s.citySize === 'megacity' ? 'too_large_for_one_centre_several_centres_grow_and_merge' : 'planned_round_several_centres'; }
    else if (roads >= 4 && s.populationTarget >= 200000) { pattern = 'RADIAL_CORRIDOR'; why = `${roads}_regional_roads_meet_here_and_growth_follows_them`; }
    else if ((s.planningProfile === 'strong_grid' || s.planningProfile === 'flat_loose') && steep.share < 0.08) { pattern = 'GRID_EXPANSION'; axis = s.orientation; why = 'flat_open_land_laid_out_in_successive_grid_extensions'; }
    else if (river.share > 0.05 && s.populationTarget < 150000) { pattern = 'BIDIRECTIONAL'; axis = river.angle + Math.PI / 2; why = 'a_river_town_grows_up_and_down_the_valley'; }
    else { pattern = 'CONCENTRIC'; why = s.planningProfile === 'centralised' || s.planningProfile === 'radial_formal' ? 'open_land_and_a_centralising_plan_growth_in_rings_round_one_core' : 'open_land_on_every_side_of_one_dominant_core'; }
    s.macroGrowthPattern = pattern; s.macroGrowthReason = why; s.macroGrowth = { pattern, reason: why, axis, bias, reachFactor: MACRO_GROWTH[pattern] };
  }
  log(`macro growth: ${Object.keys(MACRO_GROWTH).map((k) => [k, S.filter((s) => s.macroGrowthPattern === k).length]).filter(([, c]) => c).map(([k, c]) => `${c} ${k.toLowerCase()}`).join(', ')}`);
}

// ---------------------------------------------------------------- 5. interface zones
function planInterfaces(region, rng, log) {
  // No interface zones: what lies between two neighbours is their own street fabric. The stage
  // only decides how open each shared boundary is; the streets are joined after both exist.
  const S = new Map(region.settlements.map((s) => [s.id, s]));
  for (const rel of region.relations) {
    if (rel.relation === 'SEPARATE') continue;
    const a = S.get(rel.a), b = S.get(rel.b), tx = -rel.seam.ny, ty = rel.seam.nx, half = Math.min(a.radius, b.radius) * 0.95;
    [rel.seamMode, rel.seamModeReason] = seamModeOf(region, rel, a, b);
    rel.seamLine = [{ x: rel.seam.x - tx * half, y: rel.seam.y - ty * half }, { x: rel.seam.x + tx * half, y: rel.seam.y + ty * half }];
  }
  region.interfaceZones = []; // kept empty for older callers
  const adj = region.relations.filter((r) => r.seamMode);
  log(`${adj.length} shared boundaries: ${SEAM_MODES.map((m) => [m, adj.filter((r) => r.seamMode === m).length]).filter(([, c]) => c).map(([m, c]) => `${c} ${m.toLowerCase()}`).join(', ') || 'none'}`);
}

// ---------------------------------------------------------------- 6. settlements
export function settlementConfig(region, s) {
  const T = region.terrain, mapSize = s.mapSize, N = Math.round(mapSize / 50);
  const data = new Float32Array(N * N);
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) data[y * N + x] = T.elevationAt(s.origin.x + (x + 0.5) * 50, s.origin.y + (y + 0.5) * 50);
  const [lo, hi] = SIZE_PRESETS[s.citySize].popRange;
  // land on the far side of a boundary shared with a neighbour is not this settlement's
  const exclusions = [];
  for (const rel of region.relations) {
    if (!rel.windowsOverlap) continue;
    const mine = rel.a === s.id, other = rel.b === s.id;
    if (!mine && !other) continue;
    const sign = mine ? 1 : -1;
    exclusions.push({ x: rel.seam.x - s.origin.x, y: rel.seam.y - s.origin.y, nx: rel.seam.nx * sign, ny: rel.seam.ny * sign, neighbour: mine ? rel.b : rel.a });
  }
  return {
    ...DEFAULT_CONFIG, ...PLANNING_PROFILES[s.planningProfile],
    seed: `${region.seed}/${s.id}`, citySize: s.citySize, targetPopulation: clamp(s.populationTarget, lo, hi),
    heightmap: { width: N, height: N, data, metres: true },
    bypass: s.throughPairs.length ? 'always' : 'auto',
    regionalContext: { regionSeed: region.seed, settlementId: s.id, role: s.role, scale: s.scale, rank: s.rank, regionalImportance: s.regionalImportance, institutions: s.institutions, populationProfile: region.populationProfile, macroGrowth: s.macroGrowth, exclusions, gateways: s.gateways, railEntries: s.rail ? s.railEntries : [], rail: s.rail && s.railEntries.length > 0, railApproaches: s.railEntries.length, throughPairs: s.throughPairs },
  };
}

function finishSettlement(region, s) {
  const m = s.model, live = m.network.edges.filter((e) => !e.removed && e.cls !== 'rail');
  s.modelledPopulation = m.brief.population;
  s.capacityLimited = m.brief.population < s.populationTarget * 0.95;
  s.summary = {
    areaKm2: m.districts.reduce((a, d) => a + d.area, 0) / 1e6, streetKm: live.reduce((a, e) => a + e.len, 0) / 1000,
    anchors: m.anchors.reduce((o, a) => { if (a.type !== 'neighbourhood' && a.type !== 'gateway') o[a.type] = (o[a.type] || 0) + 1; return o; }, {}), builtInstitutions: m.institutions.reduce((o, a) => { o[a.type] = (o[a.type] || 0) + 1; return o; }, {}), footprint: m.brief.footprint || null, reinforcementRejected: m.reinforcement?.rejected?.length ?? 0, reinforcementLinks: m.reinforcement?.links?.length ?? 0,
    districts: m.districts.length, hasStation: !!(m.rail && m.rail.stationComplex), stationTracks: m.rail?.stationComplex?.platformTracks ?? 0, stationConfiguration: m.rail?.stationComplex?.configuration ?? null,
    railLines: m.rail ? m.rail.lines.length : 0, corridors: m.corridors.length, civicAxisAngle: m.civicComposition.axisAngle,
    regionalRoadDecisions: m.regionalRoadDecisions.map((d) => d.behaviour), warnings: m.validation.warnings.length,
  };
  // stitch: regional lines end exactly where the settlement's own roads and tracks begin
  for (const a of m.anchors) {
    if (!a.regionalRoadId) continue;
    const road = region.regionalRoads.find((r) => r.id === a.regionalRoadId), p = { x: a.position.x + s.origin.x, y: a.position.y + s.origin.y };
    if (!road) continue;
    if (road.handedOverAtSeam) { (road.seamEnds = road.seamEnds || []).push(p); continue; }
    const d0 = Math.hypot(road.points[0].x - p.x, road.points[0].y - p.y), d1 = Math.hypot(road.points[road.points.length - 1].x - p.x, road.points[road.points.length - 1].y - p.y);
    if (Math.min(d0, d1) < 6000 && !road.passesThrough.includes(s.id)) { if (d0 < d1) road.points[0] = p; else road.points[road.points.length - 1] = p; }
  }
  for (const pt of m.rail?.portals || []) {
    if (!pt.regionalRailId) continue;
    const line = region.regionalRail.find((l) => l.id === pt.regionalRailId), p = { x: pt.x + s.origin.x, y: pt.y + s.origin.y };
    if (!line) continue;
    const d0 = Math.hypot(line.points[0].x - p.x, line.points[0].y - p.y), d1 = Math.hypot(line.points[line.points.length - 1].x - p.x, line.points[line.points.length - 1].y - p.y);
    if (line.handedOverAtSeam) { line.points[line.points[0].set ? 1 : 0] = { ...p, set: true }; continue; }
    if (Math.min(d0, d1) < 4000) { if (d0 < d1) line.points[0] = p; else line.points[line.points.length - 1] = p; }
  }
}

function finishRegion(region) {
  if (region.settlements.every((s) => s.model)) stitchSeams(region); else { region.seamConnections = []; region.metropolitanCorridors = []; }
  for (const r of region.regionalRoads) { if (r.seamEnds && r.seamEnds.length >= 2) r.points = r.seamEnds.slice(0, 2); r.length = polylineLength(r.points); }
  for (const l of region.regionalRail) l.length = polylineLength(l.points);
  const S = region.settlements, by = (k) => S.reduce((o, s) => { o[s[k]] = (o[s[k]] || 0) + 1; return o; }, {});
  region.stats = {
    regionalPopulationTarget: region.regionalPopulationTarget, allocatedPopulation: S.reduce((a, s) => a + s.populationTarget, 0), modelledPopulation: S.reduce((a, s) => a + (s.modelledPopulation || 0), 0),
    settlements: S.length, byScale: by('scale'), byRole: by('role'), byCentreStrength: by('centreStrength'),
    relations: region.relations.reduce((o, r) => { o[r.relation] = (o[r.relation] || 0) + 1; return o; }, {}),
    continuousGroups: [...new Set(S.filter((s) => s.continuity !== 'FREE_STANDING').map((s) => s.urbanContinuityGroup))].length,
    largestContinuousGroup: Math.max(...Object.values(S.reduce((o, s) => { o[s.urbanContinuityGroup] = (o[s.urbanContinuityGroup] || 0) + 1; return o; }, {}))),
    regionalRoadKm: region.regionalRoads.reduce((a, r) => a + r.length, 0) / 1000, regionalRailKm: region.regionalRail.reduce((a, l) => a + l.length, 0) / 1000,
    streetKm: S.reduce((a, s) => a + (s.summary?.streetKm || 0), 0), urbanAreaKm2: S.reduce((a, s) => a + (s.summary?.areaKm2 || 0), 0),
    stations: S.filter((s) => s.summary?.hasStation).length, interfaceZones: 0, seamConnections: region.seamConnections.length, sharedBoundaries: region.relations.filter((r) => r.seamMode).length, metropolitanCorridors: region.metropolitanCorridors.length,
  };
}

const STAGES = [['terrain', planRegionTerrain], ['regionalPlan', planSettlementSystem], ['sites', planSites], ['infrastructure', planInfrastructure], ['interfaces', planInterfaces]];
function planRegion(region) {
  for (const [id, fn] of STAGES) {
    const t0 = performance.now(), messages = [];
    fn(region, new SeededRandom(region.seed).fork('region/' + id), (msg) => messages.push(msg));
    region.metadata.log.push({ stage: id, ms: performance.now() - t0, messages });
  }
}

// Everything up to and including the settlements, synchronously (tests, scripts).
export function generateRegionSync(input, { settlements = true } = {}) {
  const region = createRegionModel(input);
  planRegion(region);
  if (settlements) for (const s of region.settlements) { s.model = createCityModel(settlementConfig(region, s)); runPipelineSync(s.model); finishSettlement(region, s); }
  finishRegion(region);
  return region;
}

// The same, yielding between settlements so a UI can show progress.
export async function generateRegion(input, onProgress = null) {
  const region = createRegionModel(input);
  planRegion(region);
  let k = 0;
  for (const s of region.settlements) {
    if (onProgress) await onProgress(region, s, ++k);
    s.model = createCityModel(settlementConfig(region, s));
    await runPipeline(s.model, 'terrain', null);
    finishSettlement(region, s);
  }
  finishRegion(region);
  return region;
}
