// Builds the data side of the calibration study from the measured files:
//   reference/profiles/<city>.json   (real cities)   +   calibration/citygen-batch.json   (generated)
// -> docs/calibration/DATA_TABLES.md   every table, regenerated in full each run
// -> calibration/summary.json          the key numbers the written report cites
// No judgement is made here beyond stating where a value lies relative to the reference cities.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { METRICS, METRIC_KEYS, percentiles, quantile } from '../src/analysis/Metrics.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const corpus = JSON.parse(readFileSync(join(ROOT, 'reference/corpus.json'), 'utf8'));
// defaults measure the CURRENT generator; pass --batch / --tables / --summary to rebuild an older study
const arg = (k, d) => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? process.argv[i + 1] : d; };
const BATCH = arg('batch', 'calibration/citygen-batch.json'), TABLES = arg('tables', 'docs/calibration/DATA_TABLES_CURRENT.md'), SUMMARY = arg('summary', 'calibration/summary.json');
const batch = JSON.parse(readFileSync(join(ROOT, BATCH), 'utf8'));
const refs = corpus.cities.filter((c) => existsSync(join(ROOT, 'reference/profiles', `${c.id}.json`))).map((c) => ({ ...c, profile: JSON.parse(readFileSync(join(ROOT, 'reference/profiles', `${c.id}.json`), 'utf8')) }));
const SCALES = ['city', 'district', 'neighbourhood'];
const FOCUS = ['fourWayShare', 'threeWayShare', 'deadEndShare', 'avgNodeDegree', 'majorRoadSpacing', 'majorRoadShare', 'shareRegional', 'shareArterial', 'shareAvenue', 'shareConnector', 'shareLocal', 'segmentLengthMean', 'segmentLengthMedian', 'intersectionDensity', 'streetDensity', 'orientationEntropy', 'orientationOrder', 'dominantOrientations', 'circuity', 'blockAreaMedian', 'blockAspectMedian', 'corridorContinuity', 'majorCorridorLengthKm'];
const f = (v, key) => (v === null || v === undefined || !Number.isFinite(v) ? '–' : v.toFixed(METRICS[key] ? METRICS[key][2] : 2));
const unit = (key) => (METRICS[key][1] ? ` (${METRICS[key][1]})` : '');
const sorted = (a) => a.filter((v) => v !== null && v !== undefined && Number.isFinite(v)).sort((x, y) => x - y);

// --- the two populations, per scale and metric
// CityGen: at city scale one value per seed; at window scales the median window of each seed
// (seed-level) and every window of every seed (pooled).
const gen = {}, ref = {};
for (const s of SCALES) {
  gen[s] = {}; ref[s] = {};
  for (const k of METRIC_KEYS) {
    const seedVals = sorted(batch.cities.map((c) => c.scales[s].metrics[k]));
    gen[s][k] = { seeds: seedVals, dist: percentiles(seedVals), pooled: s === 'city' ? percentiles(seedVals) : batch.pooledWindows[s][k] };
    const cityVals = refs.map((r) => ({ id: r.id, name: r.name, archetype: r.archetype, v: r.profile.scales[s].metrics[k] })).filter((x) => x.v !== null && x.v !== undefined);
    const pooledRef = s === 'city' ? cityVals.map((x) => x.v) : refs.flatMap((r) => r.profile.scales[s].sampleList.map((sm) => sm.metrics[k]));
    const vs = sorted(cityVals.map((x) => x.v));
    ref[s][k] = { cities: cityVals, min: vs[0] ?? null, max: vs[vs.length - 1] ?? null, median: vs.length ? quantile(vs, 0.5) : null, pooled: percentiles(pooledRef) };
  }
}
// where the generated median lies relative to the envelope of the reference cities
function position(s, k) {
  const g = gen[s][k].dist, r = ref[s][k];
  if (!g || r.min === null) return { label: 'not measured', inside: null };
  const inside = gen[s][k].seeds.filter((v) => v >= r.min && v <= r.max).length / gen[s][k].seeds.length;
  let label = 'inside';
  if (g.p50 < r.min) label = `below all ${refs.length} (${r.min ? (g.p50 / r.min).toFixed(2) : '0'}x the lowest)`;
  else if (g.p50 > r.max) label = `above all ${refs.length} (${r.max ? (g.p50 / r.max).toFixed(2) : 'inf'}x the highest)`;
  return { label, inside, below: r.cities.filter((c) => c.v < g.p50).length, of: r.cities.length };
}

let md = `# Calibration data tables\n\nGenerated by \`node scripts/calibration-report.mjs\` from \`reference/profiles/\` and \`${BATCH}\` (generator: ${batch.generator}). Do not edit by hand. Interpretation: [REALISM_CALIBRATION_REPORT.md](../REALISM_CALIBRATION_REPORT.md) for the Alpha.2 study, [REALISM_BETA_CHECK.md](../REALISM_BETA_CHECK.md) for the Beta generator.\n\n`;
md += `- Reference cities: ${refs.length} (${refs.map((r) => r.name).join(', ')})\n- Generated cities: ${batch.count} seeds\n- "Envelope" = lowest to highest of the ${refs.length} reference cities (their city value, or their median window at district / neighbourhood scale).\n- "In envelope" = share of generated seeds whose value lies inside it.\n\n`;

// 1. corpus
md += `## 1. Reference corpus\n\n| City | Country | Archetype | Boundary | Area km² | Segments | Blocks | District windows | Neighbourhood windows | Extracted |\n|---|---|---|---|---|---|---|---|---|---|\n`;
for (const r of refs) {
  const p = r.profile, b = p.sourceMetadata.boundary || {};
  md += `| ${r.name} | ${r.country} | ${r.archetype} | ${b.method === 'square_window' ? `${b.window_km} km window on ${b.center_lat_lon.join(', ')}` : `administrative boundary "${b.geocode_query}"`} | ${p.scales.city.areaKm2.toFixed(0)} | ${p.network.segments} | ${p.network.blocks} | ${p.scales.district.samples} | ${p.scales.neighbourhood.samples} | ${p.sourceMetadata.extracted} |\n`;
}
md += `\nWindow contexts (neighbourhood scale), by position in the city and by fabric:\n\n| City | central | inner | peripheral | strong grid | mixed | irregular |\n|---|---|---|---|---|---|---|\n`;
const ctx = (list) => { const o = { central: 0, inner: 0, peripheral: 0, strong_grid: 0, mixed: 0, irregular: 0 }; for (const sm of list) { o[sm.context.ring]++; o[sm.context.fabric] = (o[sm.context.fabric] || 0) + 1; } return o; };
const fabricShare = {};
for (const r of refs) { const o = ctx(r.profile.scales.neighbourhood.sampleList), n = r.profile.scales.neighbourhood.samples; fabricShare[r.id] = { strong_grid: o.strong_grid / n, mixed: o.mixed / n, irregular: o.irregular / n }; md += `| ${r.name} | ${o.central} | ${o.inner} | ${o.peripheral} | ${o.strong_grid} | ${o.mixed} | ${o.irregular} |\n`; }
const genCtx = { central: 0, inner: 0, peripheral: 0, strong_grid: 0, mixed: 0, irregular: 0 };
for (const c of batch.cities) { for (const [k, v] of Object.entries(c.scales.neighbourhood.contexts.ring)) genCtx[k] += v; for (const [k, v] of Object.entries(c.scales.neighbourhood.contexts.fabric)) genCtx[k] = (genCtx[k] || 0) + v; }
md += `| **CityGen (${batch.count} seeds)** | ${genCtx.central} | ${genCtx.inner} | ${genCtx.peripheral} | ${genCtx.strong_grid} | ${genCtx.mixed} | ${genCtx.irregular} |\n\n`;
const genWindows = genCtx.strong_grid + genCtx.mixed + genCtx.irregular;

// 2. batch
const count = (key) => Object.entries(batch.cities.reduce((o, c) => { o[c[key]] = (o[c[key]] || 0) + 1; return o; }, {})).map(([k, v]) => `${k} ${v}`).join(', ');
const areas = sorted(batch.cities.map((c) => c.scales.city.areaKm2));
md += `## 2. Generated batch\n\n- Sizes: ${count('citySize')}\n- Terrain: ${count('terrainPreset')}\n- Planning profiles: ${count('planningProfile')}\n- Network area: ${areas[0].toFixed(0)}–${areas[areas.length - 1].toFixed(0)} km² (median ${quantile(areas, 0.5).toFixed(0)})\n- District windows per seed: ${quantile(sorted(batch.cities.map((c) => c.scales.district.samples)), 0.5)} (median); seeds with none: ${batch.cities.filter((c) => !c.scales.district.samples).length}\n- Neighbourhood windows per seed: ${quantile(sorted(batch.cities.map((c) => c.scales.neighbourhood.samples)), 0.5)} (median); total ${genWindows}\n\n`;

// 3. overview per scale
const summary = { refs: refs.length, seeds: batch.count, scales: {} };
md += `## 3. Every metric, by scale\n\n`;
for (const s of SCALES) {
  summary.scales[s] = {};
  md += `### ${s[0].toUpperCase() + s.slice(1)} scale\n\n${s === 'city' ? 'CityGen columns: across seeds.' : 'CityGen columns: P10 / median / P90 over every window of every seed (pooled); the reference pooled column is the same over every window of every reference city.'}\n\n`;
  md += `| Metric | CityGen P10 | CityGen median | CityGen P90 | Reference cities low–high (median) |${s === 'city' ? '' : ' Reference windows P10–P90 |'} CityGen median vs envelope | Reference cities below the CityGen median | In envelope |\n|---|---|---|---|---|${s === 'city' ? '' : '---|'}---|---|---|\n`;
  for (const k of METRIC_KEYS) {
    const g = gen[s][k].pooled, r = ref[s][k], pos = position(s, k);
    if (!g || r.min === null) continue;
    summary.scales[s][k] = { citygen: g, citygenSeedMedians: gen[s][k].dist, refMin: r.min, refMax: r.max, refMedian: r.median, refPooled: r.pooled, position: pos.label, refCitiesBelow: pos.below, inEnvelope: pos.inside, cities: Object.fromEntries(r.cities.map((c) => [c.id, c.v])) };
    md += `| ${METRICS[k][0]}${unit(k)} | ${f(g.p10, k)} | **${f(gen[s][k].dist.p50, k)}** | ${f(g.p90, k)} | ${f(r.min, k)}–${f(r.max, k)} (${f(r.median, k)}) |${s === 'city' ? '' : ` ${f(r.pooled.p10, k)}–${f(r.pooled.p90, k)} |`} ${pos.label} | ${pos.below} of ${pos.of} | ${Math.round(pos.inside * 100)}% |\n`;
  }
  md += '\n';
}

// 4. per city
md += `## 4. Focus metrics, city by city\n\n`;
for (const s of SCALES) {
  md += `### ${s[0].toUpperCase() + s.slice(1)} scale${s === 'city' ? '' : ' (median window)'}\n\n| Metric | CityGen | ${refs.map((r) => r.name).join(' | ')} |\n|---|---|${refs.map(() => '---').join('|')}|\n`;
  for (const k of FOCUS) {
    if (!gen[s][k].dist) continue;
    md += `| ${METRICS[k][0]}${unit(k)} | **${f(gen[s][k].dist.p50, k)}** | ${refs.map((r) => f(r.profile.scales[s].metrics[k], k)).join(' | ')} |\n`;
  }
  md += '\n';
}

// 5. archetypes
const archetypes = {};
for (const r of refs) for (const a of [r.archetype, ...(r.alsoContributesTo || [])]) (archetypes[a] = archetypes[a] || []).push(r);
md += `## 5. Archetype ranges\n\nLow–high of the member cities. A single-city archetype shows that city's value (its P25–P75 over windows at neighbourhood scale).\n\n`;
summary.archetypes = {};
for (const s of ['city', 'neighbourhood']) {
  md += `### ${s[0].toUpperCase() + s.slice(1)} scale\n\n| Metric | CityGen P10–P90 | ${Object.entries(archetypes).map(([a, l]) => `${a} (${l.map((r) => r.name).join(', ')})`).join(' | ')} |\n|---|---|${Object.keys(archetypes).map(() => '---').join('|')}|\n`;
  for (const k of FOCUS) {
    const g = gen[s][k].pooled;
    if (!g) continue;
    const cells = Object.entries(archetypes).map(([a, l]) => {
      const vs = sorted(l.map((r) => r.profile.scales[s].metrics[k]));
      if (!vs.length) return '–';
      let lo = vs[0], hi = vs[vs.length - 1];
      if (l.length === 1 && s !== 'city' && l[0].profile.scales[s].distributions[k]) { lo = l[0].profile.scales[s].distributions[k].p25; hi = l[0].profile.scales[s].distributions[k].p75; }
      ((summary.archetypes[a] = summary.archetypes[a] || {})[s] = summary.archetypes[a][s] || {})[k] = [lo, hi];
      const out = gen[s][k].dist.p50 < lo ? ' ▼' : gen[s][k].dist.p50 > hi ? ' ▲' : '';
      return lo === hi ? `${f(lo, k)}${out}` : `${f(lo, k)}–${f(hi, k)}${out}`;
    });
    md += `| ${METRICS[k][0]}${unit(k)} | ${f(g.p10, k)}–${f(g.p90, k)} | ${cells.join(' | ')} |\n`;
  }
  md += `\n▲ / ▼: the CityGen median is above / below that archetype's range.\n\n`;
}

// 6. variance
md += `## 6. Variance\n\n### Within one city: spread of individual elements (P90 / P10)\n\n| | Segment length | Block area | Block aspect ratio |\n|---|---|---|---|\n`;
const spread = (d) => (d && d.p10 > 0 ? d.p90 / d.p10 : null);
const elem = ['segmentLength', 'blockArea', 'blockAspect'];
summary.variance = { element: {}, window: {} };
const genSpread = Object.fromEntries(elem.map((e) => [e, percentiles(batch.cities.map((c) => spread(c.scales.city.distributions[e])))]));
md += `| **CityGen median (P10–P90 of seeds)** | ${elem.map((e) => `**${genSpread[e].p50.toFixed(1)}** (${genSpread[e].p10.toFixed(1)}–${genSpread[e].p90.toFixed(1)})`).join(' | ')} |\n`;
for (const r of refs) md += `| ${r.name} | ${elem.map((e) => spread(r.profile.scales.city.distributions[e])?.toFixed(1) ?? '–').join(' | ')} |\n`;
for (const e of elem) summary.variance.element[e] = { citygen: genSpread[e], refs: Object.fromEntries(refs.map((r) => [r.id, spread(r.profile.scales.city.distributions[e])])) };
// the same question with measures that small artefacts cannot move: interquartile ratios, and blocks of at least 0.3 ha
md += `\n### Robust versions (P75 / P25; blocks of 0.3 ha and more only)\n\nIn OpenStreetMap data, faces under 0.3 ha are often slivers between carriageways rather than blocks, and junction detail produces very short segments. These columns are insensitive to both.\n\n| | Segment length P75/P25 | Block area P75/P25 (≥ 0.3 ha) | Block aspect median (≥ 0.3 ha) | Block aspect P75 (≥ 0.3 ha) | Faces under 0.3 ha |\n|---|---|---|---|---|---|\n`;
const iqr = (d) => (d && d.p25 > 0 ? d.p75 / d.p25 : null);
const robust = (dz) => [iqr(dz.segmentLength), iqr(dz.blockAreaOver03ha), dz.blockAspectOver03ha?.p50 ?? null, dz.blockAspectOver03ha?.p75 ?? null, dz.smallFaceShare];
const genRobust = [0, 1, 2, 3, 4].map((i) => percentiles(batch.cities.map((c) => robust(c.scales.city.distributions)[i])));
md += `| **CityGen median (P10–P90 of seeds)** | ${genRobust.map((d, i) => (i === 4 ? `**${Math.round(d.p50 * 100)}%** (${Math.round(d.p10 * 100)}–${Math.round(d.p90 * 100)}%)` : `**${d.p50.toFixed(2)}** (${d.p10.toFixed(2)}–${d.p90.toFixed(2)})`)).join(' | ')} |\n`;
summary.variance.robust = { columns: ['segmentLengthIQR', 'blockAreaIQR_over03ha', 'blockAspectMedian_over03ha', 'blockAspectP75_over03ha', 'smallFaceShare'], citygen: genRobust, refs: {} };
for (const r of refs) { const v = robust(r.profile.scales.city.distributions); summary.variance.robust.refs[r.id] = v; md += `| ${r.name} | ${v.map((x, i) => (x === null ? '–' : i === 4 ? `${Math.round(x * 100)}%` : x.toFixed(2))).join(' | ')} |\n`; }
md += `\n### Within one city: how much neighbourhoods differ from each other\n\nSpread over the neighbourhood windows of one city: P90 / P10 for densities and block size, P90 − P10 for the shares and orientation order.\n\n`;
const WIN = [['intersectionDensity', 'ratio'], ['streetDensity', 'ratio'], ['blockAreaMedian', 'ratio'], ['segmentLengthMedian', 'ratio'], ['fourWayShare', 'diff'], ['deadEndShare', 'diff'], ['orientationOrder', 'diff'], ['majorRoadShare', 'diff']];
const wspread = (d, mode) => (!d ? null : mode === 'ratio' ? (d.p10 > 0 ? d.p90 / d.p10 : null) : d.p90 - d.p10);
md += `| | ${WIN.map(([k, m]) => `${METRICS[k][0]} ${m === 'ratio' ? '(ratio)' : '(range)'}`).join(' | ')} |\n|---|${WIN.map(() => '---').join('|')}|\n`;
const genW = Object.fromEntries(WIN.map(([k, m]) => [k, percentiles(batch.cities.filter((c) => c.scales.neighbourhood.samples >= 8).map((c) => wspread(c.scales.neighbourhood.distributions[k], m)))]));
md += `| **CityGen median (P10–P90 of seeds)** | ${WIN.map(([k]) => (genW[k] ? `**${genW[k].p50.toFixed(2)}** (${genW[k].p10.toFixed(2)}–${genW[k].p90.toFixed(2)})` : '–')).join(' | ')} |\n`;
for (const r of refs) md += `| ${r.name} | ${WIN.map(([k, m]) => wspread(r.profile.scales.neighbourhood.distributions[k], m)?.toFixed(2) ?? '–').join(' | ')} |\n`;
for (const [k, m] of WIN) summary.variance.window[k] = { mode: m, citygen: genW[k], refs: Object.fromEntries(refs.map((r) => [r.id, wspread(r.profile.scales.neighbourhood.distributions[k], m)])) };
md += `\n### Fabric mix of neighbourhood windows\n\nShare of 1.5 km windows whose orientation order is ≥ 0.6 (strong grid), ≤ 0.15 (irregular), or between (mixed).\n\n| | Strong grid | Mixed | Irregular |\n|---|---|---|---|\n| **CityGen** | ${Math.round((100 * genCtx.strong_grid) / genWindows)}% | ${Math.round((100 * genCtx.mixed) / genWindows)}% | ${Math.round((100 * genCtx.irregular) / genWindows)}% |\n`;
for (const r of refs) md += `| ${r.name} | ${Math.round(100 * fabricShare[r.id].strong_grid)}% | ${Math.round(100 * fabricShare[r.id].mixed)}% | ${Math.round(100 * fabricShare[r.id].irregular)}% |\n`;
summary.fabricMix = { citygen: { strong_grid: genCtx.strong_grid / genWindows, mixed: genCtx.mixed / genWindows, irregular: genCtx.irregular / genWindows }, refs: fabricShare };

// 7. by position in the city
md += `\n## 7. Neighbourhood windows by position in the city\n\nMedian window in each ring. Central = within 0.3 of the city's equivalent radius of its centre, peripheral = beyond 0.7.\n\n`;
const RINGK = ['intersectionDensity', 'fourWayShare', 'deadEndShare', 'segmentLengthMedian', 'blockAreaMedian', 'orientationOrder', 'majorRoadShare'];
summary.byRing = {};
for (const ring of ['central', 'inner', 'peripheral']) {
  md += `### ${ring}\n\n| Metric | CityGen | ${refs.map((r) => r.name).join(' | ')} |\n|---|---|${refs.map(() => '---').join('|')}|\n`;
  summary.byRing[ring] = {};
  for (const k of RINGK) {
    const cells = refs.map((r) => { const vs = sorted(r.profile.scales.neighbourhood.sampleList.filter((sm) => sm.context.ring === ring).map((sm) => sm.metrics[k])); return vs.length ? quantile(vs, 0.5) : null; });
    const g = batch.pooledNeighbourhoodByRing[ring][k];
    summary.byRing[ring][k] = { citygen: g ? g.p50 : null, refs: Object.fromEntries(refs.map((r, i) => [r.id, cells[i]])) };
    md += `| ${METRICS[k][0]}${unit(k)} | **${g ? f(g.p50, k) : '–'}** | ${cells.map((v) => f(v, k)).join(' | ')} |\n`;
  }
  md += '\n';
}

// 8. by planning profile (is any brief closer to reality?)
md += `## 8. CityGen by planning profile (city scale, median of seeds)\n\n`;
const profiles = [...new Set(batch.cities.map((c) => c.planningProfile))];
md += `| Metric | Reference low–high | ${profiles.join(' | ')} |\n|---|---|${profiles.map(() => '---').join('|')}|\n`;
summary.byPlanningProfile = {};
for (const k of ['fourWayShare', 'deadEndShare', 'majorRoadSpacing', 'majorRoadShare', 'shareConnector', 'orientationOrder', 'circuity', 'segmentLengthMedian', 'intersectionDensity', 'blockAreaMedian', 'corridorContinuity']) {
  const cells = profiles.map((p) => quantile(sorted(batch.cities.filter((c) => c.planningProfile === p).map((c) => c.scales.city.metrics[k])), 0.5));
  summary.byPlanningProfile[k] = Object.fromEntries(profiles.map((p, i) => [p, cells[i]]));
  md += `| ${METRICS[k][0]}${unit(k)} | ${f(ref.city[k].min, k)}–${f(ref.city[k].max, k)} | ${cells.map((v) => f(v, k)).join(' | ')} |\n`;
}
md += `\n### By city size\n\n| Metric | Reference low–high | ${['small', 'medium', 'major'].join(' | ')} |\n|---|---|---|---|---|\n`;
for (const k of ['fourWayShare', 'deadEndShare', 'majorRoadSpacing', 'majorRoadShare', 'shareRegional', 'corridorContinuity', 'majorCorridorLengthKm', 'intersectionDensity']) {
  md += `| ${METRICS[k][0]}${unit(k)} | ${f(ref.city[k].min, k)}–${f(ref.city[k].max, k)} | ${['small', 'medium', 'major'].map((z) => f(quantile(sorted(batch.cities.filter((c) => c.citySize === z).map((c) => c.scales.city.metrics[k])), 0.5), k)).join(' | ')} |\n`;
}

// 9. tiers combined: less sensitive to how a mapper chose between adjacent OSM classes
md += `\n## 9. Road tiers combined (% of street length)\n\nUpper = regional + arterial. Middle = avenue + connector. Combining adjacent classes makes the comparison less sensitive to how mappers chose between, say, secondary and tertiary.\n\n`;
const tiers = { upper: (m) => m.shareRegional + m.shareArterial, middle: (m) => m.shareAvenue + m.shareConnector, 'all above local': (m) => 100 - m.shareLocal };
summary.tiers = {};
for (const sc of ['city', 'neighbourhood']) {
  md += `### ${sc[0].toUpperCase() + sc.slice(1)} scale${sc === 'city' ? '' : ' (median window)'}\n\n| Tier | CityGen P10 | CityGen median | CityGen P90 | ${refs.map((r) => r.name).join(' | ')} | Reference cities below the CityGen median |\n|---|---|---|---|${refs.map(() => '---').join('|')}|---|\n`;
  summary.tiers[sc] = {};
  for (const [name, fn] of Object.entries(tiers)) {
    const g = percentiles(batch.cities.filter((c) => c.scales[sc].metrics.shareLocal !== null).map((c) => fn(c.scales[sc].metrics))), rv = refs.map((r) => fn(r.profile.scales[sc].metrics));
    summary.tiers[sc][name] = { citygen: g, refs: Object.fromEntries(refs.map((r, i) => [r.id, rv[i]])) };
    md += `| ${name} | ${g.p10.toFixed(1)} | **${g.p50.toFixed(1)}** | ${g.p90.toFixed(1)} | ${rv.map((v) => v.toFixed(1)).join(' | ')} | ${rv.filter((v) => v < g.p50).length} of ${refs.length} |\n`;
  }
  md += '\n';
}
md += `### Neighbourhood scale by planning profile (median window per seed, then median of seeds)\n\n| Metric | Reference cities low–high | ${profiles.join(' | ')} |\n|---|---|${profiles.map(() => '---').join('|')}|\n`;
summary.neighbourhoodByPlanningProfile = {};
for (const k of ['orientationOrder', 'fourWayShare', 'deadEndShare', 'circuity', 'blockAspectMedian']) {
  const cells = profiles.map((p) => quantile(sorted(batch.cities.filter((c) => c.planningProfile === p).map((c) => c.scales.neighbourhood.metrics[k])), 0.5));
  summary.neighbourhoodByPlanningProfile[k] = Object.fromEntries(profiles.map((p, i) => [p, cells[i]]));
  md += `| ${METRICS[k][0]}${unit(k)} | ${f(ref.neighbourhood[k].min, k)}–${f(ref.neighbourhood[k].max, k)} | ${cells.map((v) => f(v, k)).join(' | ')} |\n`;
}
const fabricByProfile = profiles.map((p) => { const o = { strong_grid: 0, mixed: 0, irregular: 0 }; for (const c of batch.cities.filter((x) => x.planningProfile === p)) for (const [k, v] of Object.entries(c.scales.neighbourhood.contexts.fabric)) o[k] = (o[k] || 0) + v; const n = o.strong_grid + o.mixed + o.irregular; return n ? Math.round((100 * o.strong_grid) / n) : null; });
md += `| Strong-grid windows (%) | 2–87 | ${fabricByProfile.join(' | ')} |\n`;
summary.strongGridShareByProfile = Object.fromEntries(profiles.map((p, i) => [p, fabricByProfile[i]]));

writeFileSync(join(ROOT, TABLES), md);
writeFileSync(join(ROOT, SUMMARY), JSON.stringify(summary, (k, v) => (typeof v === 'number' && !Number.isInteger(v) ? Number(v.toPrecision(5)) : v), 1));
console.log(`${TABLES} and ${SUMMARY} written (${refs.length} reference cities, ${batch.count} generated)`);
